/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';
export const DARK_MODE = 'DARK_MODE';
export const BOXED_LAYOUT = 'BOXED_LAYOUT';
export const RTL_LAYOUT = 'RTL_LAYOUT';
export const MINI_SIDEBAR = 'MINI_SIDEBAR';
export const SEARCH_FORM_ENABLE = 'SEARCH_FORM_ENABLE';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const TOGGLE_SIDEBAR_IMAGE = 'TOGGLE_SIDEBAR_IMAGE';
export const SET_SIDEBAR_IMAGE = 'SET_SIDEBAR_IMAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const START_USER_TOUR = 'START_USER_TOUR';
export const STOP_USER_TOUR = 'STOP_USER_TOUR';
export const TOGGLE_DARK_SIDENAV = 'TOGGLE_DARK_SIDENAV';

// Chat App Actions
export const CHAT_WITH_SELECTED_USER = 'CHAT_WITH_SELECTED_USER';
export const SEND_MESSAGE_TO_USER = 'SEND_MESSAGE_TO_USER';
export const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';
export const SEARCH_USERS = 'SEARCH_USERS';
export const GET_RECENT_CHAT_USERS = 'GET_RECENT_CHAT_USERS';

// Mail App
export const GET_EMAILS = 'GET_EMAILS';
export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';
export const GET_EMAIL_FAILURE = 'GET_EMAIL_FAILURE';
export const SET_EMAIL_AS_STAR = 'SET_EMAIL_AS_STAR';
export const READ_EMAIL = 'READ_EMAIL';
export const HIDE_LOADING_INDICATOR = 'HIDE_LOADING_INDICATOR';
export const FETCH_EMAILS = 'FETCH_EMAILS';
export const ON_SELECT_EMAIL = 'ON_SELECT_EMAIL';
export const UPDATE_EMAIL_SEARCH = 'UPDATE_EMAIL_SEARCH';
export const SEARCH_EMAIL = 'SEARCH_EMAIL';
export const ON_DELETE_MAIL = 'ON_DELETE_MAIL';
export const ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING = 'ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING';
export const GET_SENT_EMAILS = 'GET_SENT_EMAILS';
export const GET_INBOX = 'GET_INBOX';
export const GET_DRAFTS_EMAILS = 'GET_DRAFTS_EMAILS';
export const GET_SPAM_EMAILS = 'GET_SPAM_EMAILS';
export const GET_TRASH_EMAILS = 'GET_TRASH_EMAILS';
export const ON_EMAIL_MOVE_TO_FOLDER = 'ON_EMAIL_MOVE_TO_FOLDER';
export const SELECT_ALL_EMAILS = 'SELECT_ALL_EMAILS';
export const UNSELECT_ALL_EMAILS = 'UNSELECT_ALL_EMAILS';
export const ON_SEND_EMAIL = 'ON_SEND_EMAIL';
export const EMAIL_SENT_SUCCESSFULLY = 'EMAIL_SENT_SUCCESSFULLY';
export const FILTER_EMAILS_WITH_LABELS = 'FILTER_EMAILS_WITH_LABELS';
export const ADD_LABELS_INTO_EMAILS = 'ADD_LABELS_INTO_EMAILS';

// Sidebar
export const TOGGLE_MENU = 'TOGGLE_MENU';

// Agency Sidebar
export const AGENCY_TOGGLE_MENU = 'AGENCY_TOGGLE_MENU';
export const CHANGE_AGENCY_LAYOUT_BG = 'CHANGE_AGENCY_LAYOUT_BG';

// ToDo App
export const GET_TODOS = 'GET_TODOS';
export const FETCH_TODOS = 'FETCH_TODOS';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ON_SELECT_TODO = 'ON_SELECT_TODO';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';
export const ON_BACK_TO_TODOS = 'ON_BACK_TO_TODOS';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const MARK_AS_STAR_TODO = 'MARK_AS_STAR_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const ADD_LABELS_INTO_THE_TASK = 'ADD_LABELS_INTO_THE_TASK';
export const GET_ALL_TODO = 'GET_ALL_TODO';
export const GET_COMPLETED_TODOS = 'GET_COMPLETED_TODOS';
export const GET_DELETED_TODOS = 'GET_DELETED_TODOS';
export const GET_STARRED_TODOS = 'GET_STARRED_TODOS';
export const GET_FILTER_TODOS = 'GET_FILTER_TODOS';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE';
export const UPDATE_TASK_DESCRIPTION = 'UPDATE_TASK_DESCRIPTION';
export const CHANGE_TASK_ASSIGNER = 'CHANGE_TASK_ASSIGNER';
export const ON_CHECK_BOX_TOGGLE_TODO_ITEM = 'ON_CHECK_BOX_TOGGLE_TODO_ITEM';
export const SELECT_ALL_TODO = 'SELECT_ALL_TODO';
export const GET_UNSELECTED_ALL_TODO = 'GET_UNSELECTED_ALL_TODO';
export const SELECT_STARRED_TODO = 'SELECT_STARRED_TODO';
export const SELECT_UNSTARRED_TODO = 'SELECT_UNSTARRED_TODO';
export const ON_LABEL_SELECT = 'ON_LABEL_SELECT';
export const ON_LABEL_MENU_ITEM_SELECT = 'ON_LABEL_MENU_ITEM_SELECT';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const SEARCH_TODO = 'SEARCH_TODO';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const LOGIN_FACEBOOK_USER = 'LOGIN_FACEBOOK_USER';
export const LOGIN_GOOGLE_USER = 'LOGIN_GOOGLE_USER';
export const LOGIN_TWITTER_USER = 'LOGIN_TWITTER_USER';
export const LOGIN_GITHUB_USER = 'LOGIN_GITHUB_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

// Feedbacks
export const GET_FEEDBACKS = 'GET_FEEDBACKS';
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
export const GET_FEEDBACKS_FAILURE = 'GET_FEEDBACKS_FAILURE';
export const GET_ALL_FEEDBACKS = 'GET_ALL_FEEDBACKS';
export const ON_CHANGE_FEEDBACK_PAGE_TABS = 'ON_CHANGE_FEEDBACK_PAGE_TABS';
export const MAKE_FAVORITE_FEEDBACK = 'MAKE_FAVORITE_FEEDBACK';
export const ON_DELETE_FEEDBACK = 'ON_DELETE_FEEDBACK';
export const VIEW_FEEDBACK_DETAILS = 'VIEW_FEEDBACK_DETAILS';
export const ADD_NEW_FEEDBACK = 'ADD_NEW_FEEDBACK';
export const SHOW_FEEDBACK_LOADING_INDICATOR = 'SHOW_FEEDBACK_LOADING_INDICATOR';
export const HIDE_FEEDBACK_LOADING_INDICATOR = 'HIDE_FEEDBACK_LOADING_INDICATOR';
export const NAVIGATE_TO_BACK = 'NAVIGATE_TO_BACK';
export const REPLY_FEEDBACK = 'REPLY_FEEDBACK';
export const SEND_REPLY = 'SEND_REPLY';
export const UPDATE_SEARCH_IDEA = 'UPDATE_SEARCH_IDEA';
export const ON_SEARCH_IDEA = 'ON_SEARCH_IDEA';
export const ON_COMMENT_FEEDBACK = 'ON_COMMENT_FEEDBACK';

// ecommerce
export const ON_DELETE_ITEM_FROM_CART = 'ON_DELETE_ITEM_FROM_CART';
export const ON_QUANTITY_CHANGE = 'ON_QUANTITY_CHANGE';
export const ON_ADD_ITEM_TO_CART = 'ON_ADD_ITEM_TO_CART';

/* ========================= MY ACCOUNT ====================================== */
/* ==================== PARTHBHAI SECTION ===================== */
//Login History List (code added by Parth Jani 18-9-2018)
export const LOGIN_HISTORY_LIST = 'LOGIN_HISTORY_LIST';
export const LOGIN_HISTORY_LIST_SUCCESS = 'LOGIN_HISTORY_LIST_SUCCESS';
export const LOGIN_HISTORY_LIST_FAILURE = 'LOGIN_HISTORY_LIST_FAILURE';

//IP History List (code added by Parth Jani 18-9-2018)
export const IP_HISTORY_LIST = 'IP_HISTORY_LIST';
export const IP_HISTORY_LIST_SUCCESS = 'IP_HISTORY_LIST_SUCCESS';
export const IP_HISTORY_LIST_FAILURE = 'IP_HISTORY_LIST_FAILURE';

// Device Management actions types (code added by Parth Jani 18-9-2018)
export const DEVICE_MANAGEMENT_LIST = 'DEVICE_MANAGEMENT_LIST';
export const DEVICE_MANAGEMENT_LIST_SUCCESS = 'DEVICE_MANAGEMENT_LIST_SUCCESS';
export const DEVICE_MANAGEMENT_LIST_FAILURE = 'DEVICE_MANAGEMENT_LIST_FAILURE';

// Edit Profile actions types (code added by Parth Jani 20-9-2018)
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

// Edit Profile actions types (code added by Parth Jani 20-9-2018)
export const ANTI_PHISHING_CODE = 'ANTI_PHISHING_CODE';
export const ANTI_PHISHING_CODE_SUCCESS = 'ANTI_PHISHING_CODE_SUCCESS';
export const ANTI_PHISHING_CODE_FAILURE = 'ANTI_PHISHING_CODE_FAILURE';

/* ==================== KEVINBHAI SECTION ===================== */

//For Signup User with Email
export const SIGNUP_USERS = 'SIGNUP_USERS';
export const SIGNUP_USERS_SUCCESS = 'SIGNUP_USERS_SUCCESS';
export const SIGNUP_USERS_FAILURE = 'SIGNUP_USERS_FAILURE';

//For Signup User with Mobile
export const SIGNUP_USERS_MOBILE = 'SIGNUP_USERS_MOBILE';
export const SIGNUP_USERS_MOBILE_SUCCESS = 'SIGNUP_USERS_MOBILE_SUCCESS';
export const SIGNUP_USERS_MOBILE_FAILURE = 'SIGNUP_USERS_MOBILE_FAILURE';

//For Signup User with Blockchain
export const SIGNUP_USERS_BLOCKCHAIN = 'SIGNUP_USERS_BLOCKCHAIN';
export const SIGNUP_USERS_BLOCKCHAIN_SUCCESS = 'SIGNUP_USERS_BLOCKCHAIN_SUCCESS';
export const SIGNUP_USERS_BLOCKCHAIN_FAILURE = 'SIGNUP_USERS_BLOCKCHAIN_FAILURE';

//For Send Sms Auth
export const SEND_SMSAUTH="SEND_SMSAUTH";
export const SEND_SMSAUTH_SUCCESS="SEND_SMSAUTH_SUCCESS";
export const SEND_SMSAUTH_FAILURE="SEND_SMSAUTH_FAILURE";

//For Send Sms Auth
export const SUBMIT_SEND_SMSAUTH="SUBMIT_SEND_SMSAUTH";
export const SUBMIT_SEND_SMSAUTH_SUCCESS="SUBMIT_SEND_SMSAUTH_SUCCESS";
export const SUBMIT_SEND_SMSAUTH_FAILURE="SUBMIT_SEND_SMSAUTH_FAILURE";

//For Enable Google Auth
export const ENABLE_GOOGLE_AUTH="ENABLE_GOOGLE_AUTH";
export const ENABLE_GOOGLE_AUTH_SUCCESS="ENABLE_GOOGLE_AUTH_SUCCESS";
export const ENABLE_GOOGLE_AUTH_FAILURE="ENABLE_GOOGLE_AUTH_FAILURE";

//For Reset Password
export const RESET_PASSWORD="RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE="RESET_PASSWORD_FAILURE";

//For Change Password
export const CHANGE_PASSWORD="CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE="CHANGE_PASSWORD_FAILURE";

//For Disable Send Sms Auth
export const DISABLE_SEND_SMSAUTH="DISABLE_SEND_SMSAUTH";
export const DISABLE_SEND_SMSAUTH_SUCCESS="DISABLE_SEND_SMSAUTH_SUCCESS";
export const DISABLE_SEND_SMSAUTH_FAILURE="DISABLE_SEND_SMSAUTH_FAILURE";

//For Disable Send Sms Auth
export const DISABLE_SUBMIT_SEND_SMSAUTH="DISABLE_SUBMIT_SEND_SMSAUTH";
export const DISABLE_SUBMIT_SEND_SMSAUTH_SUCCESS="DISABLE_SUBMIT_SEND_SMSAUTH_SUCCESS";
export const DISABLE_SUBMIT_SEND_SMSAUTH_FAILURE="DISABLE_SUBMIT_SEND_SMSAUTH_FAILURE";

//For Disable Send Google Auth
export const DISABLE_SUBMIT_SEND_GOOGLEAUTH="DISABLE_SUBMIT_SEND_GOOGLEAUTH";
export const DISABLE_SUBMIT_SEND_GOOGLEAUTH_SUCCESS="DISABLE_SUBMIT_SEND_GOOGLEAUTH_SUCCESS";
export const DISABLE_SUBMIT_SEND_GOOGLEAUTH_FAILURE="DISABLE_SUBMIT_SEND_GOOGLEAUTH_FAILURE";

/* ==================== SALIMBHAI SECTION ===================== */

//2FA Authentication
export const TWO_FA_GOOGLE_AUTHENTICATION = 'TWO_FA_GOOGLE_AUTHENTICATION';
export const TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS = 'TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS';
export const TWO_FA_GOOGLE_AUTHENTICATION_FAILURE = 'TWO_FA_GOOGLE_AUTHENTICATION_FAILURE';
export const TWO_FA_SMS_AUTHENTICATION = 'TWO_FA_SMS_AUTHENTICATION';
export const TWO_FA_SMS_AUTHENTICATION_SUCCESS = 'TWO_FA_SMS_AUTHENTICATION_SUCCESS';
export const TWO_FA_SMS_AUTHENTICATION_FAILURE = 'TWO_FA_SMS_AUTHENTICATION_FAILURE';
export const SEND_SMS = 'SEND_SMS';
export const SEND_SMS_SUCCESS = 'SEND_SMS_SUCCESS';
export const SEND_SMS_FAILURE = 'SEND_SMS_FAILURE';

//Login
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_BLOCKCHAIN = 'LOGIN_BLOCKCHAIN';
export const LOGIN_BLOCKCHAIN_SUCCESS = 'LOGIN_BLOCKCHAIN_SUCCESS';
export const LOGIN_BLOCKCHAIN_FAILURE = 'LOGIN_BLOCKCHAIN_FAILURE';

//Forgot Password
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Personal Verification Form
export const PERSONAL_VERIFICATION = 'PERSONAL_VERIFICATION';
export const PERSONAL_VERIFICATION_SUCCESS = 'PERSONAL_VERIFICATION_SUCCESS';
export const PERSONAL_VERIFICATION_FAILURE = 'PERSONAL_VERIFICATION_FAILURE';

//Enterprise Verification Form
export const ENTERPRISE_VERIFICATION = 'ENTERPRISE_VERIFICATION';
export const ENTERPRISE_VERIFICATION_SUCCESS = 'ENTERPRISE_VERIFICATION_SUCCESS';
export const ENTERPRISE_VERIFICATION_FAILURE = 'ENTERPRISE_VERIFICATION_FAILURE';

//Referral Friends List
export const REFERRAL_FRIENDS_LIST = 'REFERRAL_FRIENDS_LIST';
export const REFERRAL_FRIENDS_SUCCESS = 'REFERRAL_FRIENDS_SUCCESS';
export const REFERRAL_FRIENDS_FAILURE = 'REFERRAL_FRIENDS_FAILURE';

//Referral Latest Commission History List
export const REFERRAL_LATEST_COMMISSION_HISTORY_LIST = 'REFERRAL_LATEST_COMMISSION_HISTORY_LIST';
export const REFERRAL_LATEST_COMMISSION_HISTORY_SUCCESS = 'REFERRAL_LATEST_COMMISSION_HISTORY_SUCCESS';
export const REFERRAL_LATEST_COMMISSION_HISTORY_FAILURE = 'REFERRAL_LATEST_COMMISSION_HISTORY_FAILURE';

//Activity List
export const ACTIVITY_LIST = 'ACTIVITY_LIST';
export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS';
export const ACTIVITY_LIST_FAILURE = 'ACTIVITY_LIST_FAILURE';

//API Setting Form
export const API_SETTING_CREATE = 'API_SETTING_CREATE';
export const API_SETTING_CREATE_SUCCESS = 'API_SETTING_CREATE_SUCCESS';
export const API_SETTING_CREATE_FAILURE = 'API_SETTING_CREATE_FAILURE';
export const API_SETTING_SAVE = 'API_SETTING_SAVE';
export const API_SETTING_SAVE_SUCCESS = 'API_SETTING_SAVE_SUCCESS';
export const API_SETTING_SAVE_FAILURE = 'API_SETTING_SAVE_FAILURE';
export const API_SETTING_EDIT = 'API_SETTING_EDIT';
export const API_SETTING_EDIT_SUCCESS = 'API_SETTING_EDIT_SUCCESS';
export const API_SETTING_EDIT_FAILURE = 'API_SETTING_EDIT_FAILURE';
export const API_SETTING_DELETE = 'API_SETTING_DELETE';
export const API_SETTING_DELETE_SUCCESS = 'API_SETTING_DELETE_SUCCESS';
export const API_SETTING_DELETE_FAILURE = 'API_SETTING_DELETE_FAILURE';

//Social Login
export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';


