/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
//Added by salim dt:04/04/2019
export const SET_LANGUAGE_SUCCESS = "SET_LANGUAGE_SUCCESS";
export const SET_LANGUAGE_FAILURE = "SET_LANGUAGE_FAILURE";
export const START_USER_TOUR = "START_USER_TOUR";
export const STOP_USER_TOUR = "STOP_USER_TOUR";
export const TOGGLE_DARK_SIDENAV = "TOGGLE_DARK_SIDENAV";

// Chat App Actions
export const CHAT_WITH_SELECTED_USER = "CHAT_WITH_SELECTED_USER";
export const SEND_MESSAGE_TO_USER = "SEND_MESSAGE_TO_USER";
export const UPDATE_USERS_SEARCH = "UPDATE_USERS_SEARCH";
export const SEARCH_USERS = "SEARCH_USERS";
export const GET_RECENT_CHAT_USERS = "GET_RECENT_CHAT_USERS";

// Sidebar
export const TOGGLE_MENU = "TOGGLE_MENU";

// Agency Sidebar
export const AGENCY_TOGGLE_MENU = "AGENCY_TOGGLE_MENU";
export const CHANGE_AGENCY_LAYOUT_BG = "CHANGE_AGENCY_LAYOUT_BG";

// Feedbacks
export const GET_FEEDBACKS = "GET_FEEDBACKS";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";
export const GET_FEEDBACKS_FAILURE = "GET_FEEDBACKS_FAILURE";
export const GET_ALL_FEEDBACKS = "GET_ALL_FEEDBACKS";
export const ON_CHANGE_FEEDBACK_PAGE_TABS = "ON_CHANGE_FEEDBACK_PAGE_TABS";
export const MAKE_FAVORITE_FEEDBACK = "MAKE_FAVORITE_FEEDBACK";
export const ON_DELETE_FEEDBACK = "ON_DELETE_FEEDBACK";
export const VIEW_FEEDBACK_DETAILS = "VIEW_FEEDBACK_DETAILS";
export const ADD_NEW_FEEDBACK = "ADD_NEW_FEEDBACK";
export const SHOW_FEEDBACK_LOADING_INDICATOR = "SHOW_FEEDBACK_LOADING_INDICATOR";
export const HIDE_FEEDBACK_LOADING_INDICATOR = "HIDE_FEEDBACK_LOADING_INDICATOR";
export const NAVIGATE_TO_BACK = "NAVIGATE_TO_BACK";
export const REPLY_FEEDBACK = "REPLY_FEEDBACK";
export const SEND_REPLY = "SEND_REPLY";
export const UPDATE_SEARCH_IDEA = "UPDATE_SEARCH_IDEA";
export const ON_SEARCH_IDEA = "ON_SEARCH_IDEA";
export const ON_COMMENT_FEEDBACK = "ON_COMMENT_FEEDBACK";

// ecommerce
export const ON_DELETE_ITEM_FROM_CART = "ON_DELETE_ITEM_FROM_CART";
export const ON_QUANTITY_CHANGE = "ON_QUANTITY_CHANGE";
export const ON_ADD_ITEM_TO_CART = "ON_ADD_ITEM_TO_CART";

// PageContent App
export const GET_PAGE_CONTENTS = "GET_PAGE_CONTENTS";
export const GET_PAGE_CONTENTS_SUCCESS = "GET_PAGE_CONTENTS_SUCCESS";
export const GET_PAGE_CONTENTS_FAILURE = "GET_PAGE_CONTENTS_FAILURE";

// code by devang

/* ========================= MY ACCOUNT ====================================== */
/* ==================== PARTHBHAI SECTION ===================== */
//Login History List (code added by Parth Jani 18-9-2018)
export const LOGIN_HISTORY_LIST = "LOGIN_HISTORY_LIST";
export const LOGIN_HISTORY_LIST_SUCCESS = "LOGIN_HISTORY_LIST_SUCCESS";
export const LOGIN_HISTORY_LIST_FAILURE = "LOGIN_HISTORY_LIST_FAILURE";

//IP History List (code added by Parth Jani 18-9-2018)
export const IP_HISTORY_LIST = "IP_HISTORY_LIST";
export const IP_HISTORY_LIST_SUCCESS = "IP_HISTORY_LIST_SUCCESS";
export const IP_HISTORY_LIST_FAILURE = "IP_HISTORY_LIST_FAILURE";

// Device Management actions types (code added by Parth Jani 18-9-2018)
export const DEVICE_MANAGEMENT_LIST = "DEVICE_MANAGEMENT_LIST";
export const DEVICE_MANAGEMENT_LIST_SUCCESS = "DEVICE_MANAGEMENT_LIST_SUCCESS";
export const DEVICE_MANAGEMENT_LIST_FAILURE = "DEVICE_MANAGEMENT_LIST_FAILURE";

// Edit Profile actions types (code added by Parth Jani 20-9-2018)
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";
//Added by salim..
export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
export const GET_PROFILE_BY_ID_SUCCESS = "GET_PROFILE_BY_ID_SUCCESS";
export const GET_PROFILE_BY_ID_FAILURE = "GET_PROFILE_BY_ID_FAILURE";

// Edit Profile actions types (code added by Parth Jani 20-9-2018)
export const ANTI_PHISHING_CODE = "ANTI_PHISHING_CODE";
export const ANTI_PHISHING_CODE_SUCCESS = "ANTI_PHISHING_CODE_SUCCESS";
export const ANTI_PHISHING_CODE_FAILURE = "ANTI_PHISHING_CODE_FAILURE";

/* ==================== KEVINBHAI SECTION ===================== */

//For Signup User with Email
export const SIGNUP_USERS = "SIGNUP_USERS";
export const SIGNUP_USERS_SUCCESS = "SIGNUP_USERS_SUCCESS";
export const SIGNUP_USERS_FAILURE = "SIGNUP_USERS_FAILURE";

//For Signup User with Mobile
export const SIGNUP_USERS_MOBILE = "SIGNUP_USERS_MOBILE";
export const SIGNUP_USERS_MOBILE_SUCCESS = "SIGNUP_USERS_MOBILE_SUCCESS";
export const SIGNUP_USERS_MOBILE_FAILURE = "SIGNUP_USERS_MOBILE_FAILURE";

//For Signup User with Blockchain
export const SIGNUP_USERS_BLOCKCHAIN = "SIGNUP_USERS_BLOCKCHAIN";
export const SIGNUP_USERS_BLOCKCHAIN_SUCCESS = "SIGNUP_USERS_BLOCKCHAIN_SUCCESS";
export const SIGNUP_USERS_BLOCKCHAIN_FAILURE = "SIGNUP_USERS_BLOCKCHAIN_FAILURE";

//For Send Sms Auth
export const SEND_SMSAUTH = "SEND_SMSAUTH";
export const SEND_SMSAUTH_SUCCESS = "SEND_SMSAUTH_SUCCESS";
export const SEND_SMSAUTH_FAILURE = "SEND_SMSAUTH_FAILURE";

//For Send Sms Auth
export const SUBMIT_SEND_SMSAUTH = "SUBMIT_SEND_SMSAUTH";
export const SUBMIT_SEND_SMSAUTH_SUCCESS = "SUBMIT_SEND_SMSAUTH_SUCCESS";
export const SUBMIT_SEND_SMSAUTH_FAILURE = "SUBMIT_SEND_SMSAUTH_FAILURE";

//For Enable Google Auth
export const GET_GOOGLE_AUTH_INFO = "GET_GOOGLE_AUTH_INFO";
export const GET_GOOGLE_AUTH_INFO_SUCCESS = "GET_GOOGLE_AUTH_INFO_SUCCESS";
export const GET_GOOGLE_AUTH_INFO_FAILURE = "GET_GOOGLE_AUTH_INFO_FAILURE";
export const ENABLE_GOOGLE_AUTH = "ENABLE_GOOGLE_AUTH";
export const ENABLE_GOOGLE_AUTH_SUCCESS = "ENABLE_GOOGLE_AUTH_SUCCESS";
export const ENABLE_GOOGLE_AUTH_FAILURE = "ENABLE_GOOGLE_AUTH_FAILURE";

//For Reset Password
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

//For Change Password
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

//For Disable Send Sms Auth
export const DISABLE_SEND_SMSAUTH = "DISABLE_SEND_SMSAUTH";
export const DISABLE_SEND_SMSAUTH_SUCCESS = "DISABLE_SEND_SMSAUTH_SUCCESS";
export const DISABLE_SEND_SMSAUTH_FAILURE = "DISABLE_SEND_SMSAUTH_FAILURE";

//For Disable Send Sms Auth
export const DISABLE_SUBMIT_SEND_SMSAUTH = "DISABLE_SUBMIT_SEND_SMSAUTH";
export const DISABLE_SUBMIT_SEND_SMSAUTH_SUCCESS = "DISABLE_SUBMIT_SEND_SMSAUTH_SUCCESS";
export const DISABLE_SUBMIT_SEND_SMSAUTH_FAILURE = "DISABLE_SUBMIT_SEND_SMSAUTH_FAILURE";

//For Disable Send Google Auth
export const DISABLE_GOOGLE_AUTH = "DISABLE_GOOGLE_AUTH";
export const DISABLE_GOOGLE_AUTH_SUCCESS = "DISABLE_GOOGLE_AUTH_SUCCESS";
export const DISABLE_GOOGLE_AUTH_FAILURE = "DISABLE_GOOGLE_AUTH_FAILURE";

//For Membership Level
export const MEMBERSHIP_LEVEL = "MEMBERSHIP_LEVEL";
export const MEMBERSHIP_LEVEL_SUCCESS = "MEMBERSHIP_LEVEL_SUCCESS";
export const MEMBERSHIP_LEVEL_FAILURE = "MEMBERSHIP_LEVEL_FAILURE";

//For Trade Summary
export const LIST_TRADE_SUMMARY = "LIST_TRADE_SUMMARY";
export const LIST_TRADE_SUMMARY_SUCCESS = "LIST_TRADE_SUMMARY_SUCCESS";
export const LIST_TRADE_SUMMARY_FAILURE = "LIST_TRADE_SUMMARY_FAILURE";

//For Top Gainers
export const LIST_TOP_GAINERS = "LIST_TOP_GAINERS";
export const LIST_TOP_GAINERS_SUCCESS = "LIST_TOP_GAINERS_SUCCESS";
export const LIST_TOP_GAINERS_FAILURE = "LIST_TOP_GAINERS_FAILURE";

//For Top Losers
export const LIST_TOP_LOSERS = "LIST_TOP_LOSERS";
export const LIST_TOP_LOSERS_SUCCESS = "LIST_TOP_LOSERS_SUCCESS";
export const LIST_TOP_LOSERS_FAILURE = "LIST_TOP_LOSERS_FAILURE";

//For Ip Whitelist
export const LIST_IP_WHITELIST = "LIST_IP_WHITELIST";
export const LIST_IP_WHITELIST_SUCCESS = "LIST_IP_WHITELIST_SUCCESS";
export const LIST_IP_WHITELIST_FAILURE = "LIST_IP_WHITELIST_FAILURE";

//For Add IP to WhiteList
export const ADD_IP_TO_WHITELIST = "ADD_IP_TO_WHITELIST";
export const ADD_IP_TO_WHITELIST_SUCCESS = "ADD_IP_TO_WHITELIST_SUCCESS";
export const ADD_IP_TO_WHITELIST_FAILURE = "ADD_IP_TO_WHITELIST_FAILURE";

//For Delete IP to WhiteList
export const DELETE_IP_TO_WHITELIST = "DELETE_IP_TO_WHITELIST";
export const DELETE_IP_TO_WHITELIST_SUCCESS = "DELETE_IP_TO_WHITELIST_SUCCESS";
export const DELETE_IP_TO_WHITELIST_FAILURE = "DELETE_IP_TO_WHITELIST_FAILURE";

//For Disable IP to WhiteList
export const DISABLE_IP_TO_WHITELIST = "DISABLE_IP_TO_WHITELIST";
export const DISABLE_IP_TO_WHITELIST_SUCCESS = "DISABLE_IP_TO_WHITELIST_SUCCESS";
export const DISABLE_IP_TO_WHITELIST_FAILURE = "DISABLE_IP_TO_WHITELIST_FAILURE";

//For Enable IP to WhiteList
export const ENABLE_IP_TO_WHITELIST = "ENABLE_IP_TO_WHITELIST";
export const ENABLE_IP_TO_WHITELIST_SUCCESS = "ENABLE_IP_TO_WHITELIST_SUCCESS";
export const ENABLE_IP_TO_WHITELIST_FAILURE = "ENABLE_IP_TO_WHITELIST_FAILURE";

//List  WhiteList
export const LIST_DEVICE_WHITELIST = "LIST_DEVICE_WHITELIST";
export const LIST_DEVICE_WHITELIST_SUCCESS = "LIST_DEVICE_WHITELIST_SUCCESS";
export const LIST_DEVICE_WHITELIST_FAILURE = "LIST_DEVICE_WHITELIST_FAILURE";

//Add Device WhiteList
export const ADD_DEVICE_WHITELIST = "ADD_DEVICE_WHITELIST";
export const ADD_DEVICE_WHITELIST_SUCCESS = "ADD_DEVICE_WHITELIST_SUCCESS";
export const ADD_DEVICE_WHITELIST_FAILURE = "ADD_DEVICE_WHITELIST_FAILURE";

//Delete Device WhiteList
export const DELETE_DEVICE_WHITELIST = "DELETE_DEVICE_WHITELIST";
export const DELETE_DEVICE_WHITELIST_SUCCESS = "DELETE_DEVICE_WHITELIST_SUCCESS";
export const DELETE_DEVICE_WHITELIST_FAILURE = "DELETE_DEVICE_WHITELIST_FAILURE";

//Enable Device WhiteList
export const ENABLE_DEVICE_WHITELIST = "ENABLE_DEVICE_WHITELIST";
export const ENABLE_DEVICE_WHITELIST_SUCCESS = "ENABLE_DEVICE_WHITELIST_SUCCESS";
export const ENABLE_DEVICE_WHITELIST_FAILURE = "ENABLE_DEVICE_WHITELIST_FAILURE";

//Disable Device WhiteList
export const DISABLE_DEVICE_WHITELIST = "DISABLE_DEVICE_WHITELIST";
export const DISABLE_DEVICE_WHITELIST_SUCCESS = "DISABLE_DEVICE_WHITELIST_SUCCESS";
export const DISABLE_DEVICE_WHITELIST_FAILURE = "DISABLE_DEVICE_WHITELIST_FAILURE";

//Theme Configuration Get Language List
export const GET_LANGUAGE_LIST = "GET_LANGUAGE_LIST";
export const GET_LANGUAGE_LIST_SUCCESS = "GET_LANGUAGE_LIST_SUCCESS";
export const GET_LANGUAGE_LIST_FAILURE = "GET_LANGUAGE_LIST_FAILURE";

//Theme Configuration
export const SUBMIT_THEME_CONFIG = "SUBMIT_THEME_CONFIG";
export const SUBMIT_THEME_CONFIG_SUCCESS = "SUBMIT_THEME_CONFIG_SUCCESS";
export const SUBMIT_THEME_CONFIG_FAILURE = "SUBMIT_THEME_CONFIG_FAILURE";

//Forgot Confirmation
export const FORGOT_CONFIRMATION = "FORGOT_CONFIRMATION";
export const FORGOT_CONFIRMATION_SUCCESS = "FORGOT_CONFIRMATION_SUCCESS";
export const FORGOT_CONFIRMATION_FAILURE = "FORGOT_CONFIRMATION_FAILURE";

//Get Complain Type
export const GET_COMPLAIN_TYPE = "GET_COMPLAIN_TYPE";
export const GET_COMPLAIN_TYPE_SUCCESS = "GET_COMPLAIN_TYPE_SUCCESS";
export const GET_COMPLAIN_TYPE_FAILURE = "GET_COMPLAIN_TYPE_FAILURE";

//Get Complain Priority
export const GET_COMPLAIN_PRIORITY = "GET_COMPLAIN_PRIORITY";
export const GET_COMPLAIN_PRIORITY_SUCCESS = "GET_COMPLAIN_PRIORITY_SUCCESS";
export const GET_COMPLAIN_PRIORITY_FAILURE = "GET_COMPLAIN_PRIORITY_FAILURE";

/* ==================== SALIMBHAI SECTION ===================== */

//2FA Authentication
export const TWO_FA_GOOGLE_AUTHENTICATION = "TWO_FA_GOOGLE_AUTHENTICATION";
export const TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS = "TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS";
export const TWO_FA_GOOGLE_AUTHENTICATION_FAILURE = "TWO_FA_GOOGLE_AUTHENTICATION_FAILURE";
export const TWO_FA_SMS_AUTHENTICATION = "TWO_FA_SMS_AUTHENTICATION";
export const TWO_FA_SMS_AUTHENTICATION_SUCCESS = "TWO_FA_SMS_AUTHENTICATION_SUCCESS";
export const TWO_FA_SMS_AUTHENTICATION_FAILURE = "TWO_FA_SMS_AUTHENTICATION_FAILURE";
export const SEND_SMS = "SEND_SMS";
export const SEND_SMS_SUCCESS = "SEND_SMS_SUCCESS";
export const SEND_SMS_FAILURE = "SEND_SMS_FAILURE";

//Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_BLOCKCHAIN = "LOGIN_BLOCKCHAIN";
export const LOGIN_BLOCKCHAIN_SUCCESS = "LOGIN_BLOCKCHAIN_SUCCESS";
export const LOGIN_BLOCKCHAIN_FAILURE = "LOGIN_BLOCKCHAIN_FAILURE";

//Forgot Password
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

//Personal Verification Form
export const PERSONAL_VERIFICATION = "PERSONAL_VERIFICATION";
export const PERSONAL_VERIFICATION_SUCCESS = "PERSONAL_VERIFICATION_SUCCESS";
export const PERSONAL_VERIFICATION_FAILURE = "PERSONAL_VERIFICATION_FAILURE";

//Added Get KYC Status by salim dt:24-01-2019
export const GET_KYC_STATUS = "GET_KYC_STATUS";
export const GET_KYC_STATUS_SUCCESS = "GET_KYC_STATUS_SUCCESS";
export const GET_KYC_STATUS_FAILURE = "GET_KYC_STATUS_FAILURE";

//Enterprise Verification Form
export const ENTERPRISE_VERIFICATION = "ENTERPRISE_VERIFICATION";
export const ENTERPRISE_VERIFICATION_SUCCESS = "ENTERPRISE_VERIFICATION_SUCCESS";
export const ENTERPRISE_VERIFICATION_FAILURE = "ENTERPRISE_VERIFICATION_FAILURE";

//Referral Friends List
export const REFERRAL_FRIENDS_LIST = "REFERRAL_FRIENDS_LIST";
export const REFERRAL_FRIENDS_SUCCESS = "REFERRAL_FRIENDS_SUCCESS";
export const REFERRAL_FRIENDS_FAILURE = "REFERRAL_FRIENDS_FAILURE";

//Referral Latest Commission History List
export const REFERRAL_LATEST_COMMISSION_HISTORY_LIST = "REFERRAL_LATEST_COMMISSION_HISTORY_LIST";
export const REFERRAL_LATEST_COMMISSION_HISTORY_SUCCESS = "REFERRAL_LATEST_COMMISSION_HISTORY_SUCCESS";
export const REFERRAL_LATEST_COMMISSION_HISTORY_FAILURE = "REFERRAL_LATEST_COMMISSION_HISTORY_FAILURE";

//Activity List
export const ACTIVITY_LIST = "ACTIVITY_LIST";
export const ACTIVITY_LIST_SUCCESS = "ACTIVITY_LIST_SUCCESS";
export const ACTIVITY_LIST_FAILURE = "ACTIVITY_LIST_FAILURE";

//API Setting Form
export const API_SETTING_CREATE = "API_SETTING_CREATE";
export const API_SETTING_CREATE_SUCCESS = "API_SETTING_CREATE_SUCCESS";
export const API_SETTING_CREATE_FAILURE = "API_SETTING_CREATE_FAILURE";
export const API_SETTING_SAVE = "API_SETTING_SAVE";
export const API_SETTING_SAVE_SUCCESS = "API_SETTING_SAVE_SUCCESS";
export const API_SETTING_SAVE_FAILURE = "API_SETTING_SAVE_FAILURE";
export const API_SETTING_EDIT = "API_SETTING_EDIT";
export const API_SETTING_EDIT_SUCCESS = "API_SETTING_EDIT_SUCCESS";
export const API_SETTING_EDIT_FAILURE = "API_SETTING_EDIT_FAILURE";
export const API_SETTING_DELETE = "API_SETTING_DELETE";
export const API_SETTING_DELETE_SUCCESS = "API_SETTING_DELETE_SUCCESS";
export const API_SETTING_DELETE_FAILURE = "API_SETTING_DELETE_FAILURE";

//Social Login
export const SOCIAL_LOGIN = "SOCIAL_LOGIN";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SOCIAL_LOGIN_FAILURE = "SOCIAL_LOGIN_FAILURE";

//Complain
export const LIST_COMPLAIN = "LIST_COMPLAIN";
export const LIST_COMPLAIN_SUCCESS = "LIST_COMPLAIN_SUCCESS";
export const LIST_COMPLAIN_FAILURE = "LIST_COMPLAIN_FAILURE";
export const ADD_COMPLAIN = "ADD_COMPLAIN";
export const ADD_COMPLAIN_SUCCESS = "ADD_COMPLAIN_SUCCESS";
export const ADD_COMPLAIN_FAILURE = "ADD_COMPLAIN_FAILURE";
export const GET_COMPLAIN_BY_ID = "GET_COMPLAIN_BY_ID";
export const GET_COMPLAIN_BY_ID_SUCCESS = "GET_COMPLAIN_BY_ID_SUCCESS";
export const GET_COMPLAIN_BY_ID_FAILURE = "GET_COMPLAIN_BY_ID_FAILURE";
export const REPLAY_COMPLAIN = "REPLAY_COMPLAIN";
export const REPLAY_COMPLAIN_SUCCESS = "REPLAY_COMPLAIN_SUCCESS";
export const REPLAY_COMPLAIN_FAILURE = "REPLAY_COMPLAIN_FAILURE";

//Normal Registration
export const NORMAL_REGISTER = "NORMAL_REGISTER";
export const NORMAL_REGISTER_SUCCESS = "NORMAL_REGISTER_SUCCESS";
export const NORMAL_REGISTER_FAILURE = "NORMAL_REGISTER_FAILURE";
export const RESEND_CONFIRMATION_LINK = "RESEND_CONFIRMATION_LINK";
export const RESEND_CONFIRMATION_LINK_SUCCESS =
    "RESEND_CONFIRMATION_LINK_SUCCESS";
export const RESEND_CONFIRMATION_LINK_FAILURE =
    "RESEND_CONFIRMATION_LINK_FAILURE";

//SignUp Email With OTP
export const SIGNUP_WITH_EMAIL = "SIGNUP_WITH_EMAIL";
export const SIGNUP_WITH_EMAIL_SUCCESS = "SIGNUP_WITH_EMAIL_SUCCESS";
export const SIGNUP_WITH_EMAIL_FAILURE = "SIGNUP_WITH_EMAIL_FAILURE";
export const SIGNUP_EMAIL_RESEND_OTP = "SIGNUP_EMAIL_RESEND_OTP";
export const SIGNUP_EMAIL_RESEND_OTP_SUCCESS = "SIGNUP_EMAIL_RESEND_OTP_SUCCESS";
export const SIGNUP_EMAIL_RESEND_OTP_FAILURE = "SIGNUP_EMAIL_RESEND_OTP_FAILURE";
export const SIGNUP_EMAIL_VERIFY_OTP = "SIGNUP_EMAIL_VERIFY_OTP";
export const SIGNUP_EMAIL_VERIFY_OTP_SUCCESS = "SIGNUP_EMAIL_VERIFY_OTP_SUCCESS";
export const SIGNUP_EMAIL_VERIFY_OTP_FAILURE = "SIGNUP_EMAIL_VERIFY_OTP_FAILURE";

//SignUp Mobile With OTP
export const SIGNUP_WITH_MOBILE = "SIGNUP_WITH_MOBILE";
export const SIGNUP_WITH_MOBILE_SUCCESS = "SIGNUP_WITH_MOBILE_SUCCESS";
export const SIGNUP_WITH_MOBILE_FAILURE = "SIGNUP_WITH_MOBILE_FAILURE";
export const SIGNUP_MOBILE_RESEND_OTP = "SIGNUP_MOBILE_RESEND_OTP";
export const SIGNUP_MOBILE_RESEND_OTP_SUCCESS = "SIGNUP_MOBILE_RESEND_OTP_SUCCESS";
export const SIGNUP_MOBILE_RESEND_OTP_FAILURE = "SIGNUP_MOBILE_RESEND_OTP_FAILURE";
export const SIGNUP_MOBILE_VERIFY_OTP = "SIGNUP_MOBILE_VERIFY_OTP";
export const SIGNUP_MOBILE_VERIFY_OTP_SUCCESS = "SIGNUP_MOBILE_VERIFY_OTP_SUCCESS";
export const SIGNUP_MOBILE_VERIFY_OTP_FAILURE = "SIGNUP_MOBILE_VERIFY_OTP_FAILURE";

//Normal Login
export const NORMAL_LOGIN = "NORMAL_LOGIN";
export const NORMAL_LOGIN_SUCCESS = "NORMAL_LOGIN_SUCCESS";
export const NORMAL_LOGIN_FAILURE = "NORMAL_LOGIN_FAILURE";

//SignIn Email With OTP
export const SIGNIN_WITH_EMAIL = "SIGNIN_WITH_EMAIL";
export const SIGNIN_WITH_EMAIL_SUCCESS = "SIGNIN_WITH_EMAIL_SUCCESS";
export const SIGNIN_WITH_EMAIL_FAILURE = "SIGNIN_WITH_EMAIL_FAILURE";
export const SIGNIN_EMAIL_RESEND_OTP = "SIGNIN_EMAIL_RESEND_OTP";
export const SIGNIN_EMAIL_RESEND_OTP_SUCCESS = "SIGNIN_EMAIL_RESEND_OTP_SUCCESS";
export const SIGNIN_EMAIL_RESEND_OTP_FAILURE = "SIGNIN_EMAIL_RESEND_OTP_FAILURE";
export const SIGNIN_EMAIL_VERIFY_OTP = "SIGNIN_EMAIL_VERIFY_OTP";
export const SIGNIN_EMAIL_VERIFY_OTP_SUCCESS = "SIGNIN_EMAIL_VERIFY_OTP_SUCCESS";
export const SIGNIN_EMAIL_VERIFY_OTP_FAILURE = "SIGNIN_EMAIL_VERIFY_OTP_FAILURE";

//SignIn Mobile With OTP
export const SIGNIN_WITH_MOBILE = "SIGNIN_WITH_MOBILE";
export const SIGNIN_WITH_MOBILE_SUCCESS = "SIGNIN_WITH_MOBILE_SUCCESS";
export const SIGNIN_WITH_MOBILE_FAILURE = "SIGNIN_WITH_MOBILE_FAILURE";
export const SIGNIN_MOBILE_RESEND_OTP = "SIGNIN_MOBILE_RESEND_OTP";
export const SIGNIN_MOBILE_RESEND_OTP_SUCCESS = "SIGNIN_MOBILE_RESEND_OTP_SUCCESS";
export const SIGNIN_MOBILE_RESEND_OTP_FAILURE = "SIGNIN_MOBILE_RESEND_OTP_FAILURE";
export const SIGNIN_MOBILE_VERIFY_OTP = "SIGNIN_MOBILE_VERIFY_OTP";
export const SIGNIN_MOBILE_VERIFY_OTP_SUCCESS = "SIGNIN_MOBILE_VERIFY_OTP_SUCCESS";
export const SIGNIN_MOBILE_VERIFY_OTP_FAILURE = "SIGNIN_MOBILE_VERIFY_OTP_FAILURE";

//Normal Login
export const GENERATE_TOKEN = "GENERATE_TOKEN";
export const GENERATE_TOKEN_SUCCESS = "GENERATE_TOKEN_SUCCESS";
export const GENERATE_TOKEN_FAILURE = "GENERATE_TOKEN_FAILURE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS";
export const CHECK_TOKEN_FAILURE = "CHECK_TOKEN_FAILURE";

//Signup With Block chain
export const SIGNUP_WITH_BLOCKCHAIN = "SIGNUP_WITH_BLOCKCHAIN";
export const SIGNUP_WITH_BLOCKCHAIN_SUCCESS = "SIGNUP_WITH_BLOCKCHAIN_SUCCESS";
export const SIGNUP_WITH_BLOCKCHAIN_FAILURE = "SIGNUP_WITH_BLOCKCHAIN_FAILURE";

//Email Confirmation
export const EMAIL_CONFIRMATION = "EMAIL_CONFIRMATION";
export const EMAIL_CONFIRMATION_SUCCESS = "EMAIL_CONFIRMATION_SUCCESS";
export const EMAIL_CONFIRMATION_FAILURE = "EMAIL_CONFIRMATION_FAILURE";

//Device Authorize...
export const DEVICE_AUTHORIZE = "DEVICE_AUTHORIZE";
export const DEVICE_AUTHORIZE_SUCCESS = "DEVICE_AUTHORIZE_SUCCESS";
export const DEVICE_AUTHORIZE_FAILURE = "DEVICE_AUTHORIZE_FAILURE";

/* ==================== End My Account Section ===================== */

// Actions Types For PairActions For Get Pair (tejas)
export const GET_PAIR = "GET_PAIR";
export const GET_PAIR_SUCCESS = "GET_PAIR_SUCCESS";
export const GET_PAIR_FAILURE = "GET_PAIR_FAILURE";

// Actions Types For PairActions For Update Pair (tejas)
export const UPDATE_PAIR = "UPDATE_PAIR";
export const UPDATE_PAIR_SUCCESS = "UPDATE_PAIR_SUCCESS";
export const UPDATE_PAIR_FAILURE = "UPDATE_PAIR_FAILURE";

// Actions Types For PairActions For Add Task (tejas)
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

// Actions Types For PairActions For Get Task (tejas)
export const GET_TASK = "GET_TASK";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILURE = "GET_TASK_FAILURE";

// Actions Types For Pair List Actions For Get Pair  By Tejas Date : 14/9/2018
export const GET_PAIR_LIST = "GET_PAIR_LIST";
export const GET_PAIR_LIST_SUCCESS = "GET_PAIR_LIST_SUCCESS";
export const GET_PAIR_LIST_FAILURE = "GET_PAIR_LIST_FAILURE";

// Action Types For Get VolumeData By Tejas
export const GET_VOLUME_DATA = "GET_VOLUME_DATA";
export const GET_VOLUME_DATA_SUCCESS = "GET_VOLUME_DATA_SUCCESS";
export const GET_VOLUME_DATA_FAILURE = "GET_VOLUME_DATA_FAILURE";

// Actions Types For HOLDING List Actions For Get HOLDING  By Tejas Date : 14/9/2018
export const GET_HOLDING_LIST = "GET_HOLDING_LIST";
export const GET_HOLDING_LIST_SUCCESS = "GET_HOLDING_LIST_SUCCESS";
export const GET_HOLDING_LIST_FAILURE = "GET_HOLDING_LIST_FAILURE";

// Actions Types For Buyer Order List Actions For Get Buyer Order By Tejas Date : 14/9/2018
export const GET_BUYER_ORDER_LIST = "GET_BUYER_ORDER_LIST";
export const GET_BUYER_ORDER_LIST_SUCCESS = "GET_BUYER_ORDER_LIST_SUCCESS";
export const GET_BUYER_ORDER_LIST_FAILURE = "GET_BUYER_ORDER_LIST_FAILURE";
export const CHANGE_BUY_PAIR_SOCKET = "CHANGE_BUY_PAIR_SOCKET"; // added by devang parekh for re connect when pair changed

// Actions Types For Seller Order List Actions For Get Seller Order By Tejas Date : 14/9/2018
export const GET_SELLER_ORDER_LIST = "GET_SELLER_ORDER_LIST";
export const GET_SELLER_ORDER_LIST_SUCCESS = "GET_SELLER_ORDER_LIST_SUCCESS";
export const GET_SELLER_ORDER_LIST_FAILURE = "GET_SELLER_ORDER_LIST_FAILURE";
export const CHANGE_SELL_PAIR_SOCKET = "CHANGE_SELL_PAIR_SOCKET"; // added by devang parekh for re connect when pair changed

// Actions Types For Market Trade History Actions For Get Market Trade History By Tejas Date : 14/9/2018
export const GET_MARKET_TRADE_HISTORY = "GET_MARKET_TRADE_HISTORY";
export const GET_MARKET_TRADE_HISTORY_SUCCESS = "GET_MARKET_TRADE_HISTORY_SUCCESS";
export const GET_MARKET_TRADE_HISTORY_FAILURE = "GET_MARKET_TRADE_HISTORY_FAILURE";
export const CHANGE_MARKET_TRADE_HISTORY_SOCKET = "CHANGE_MARKET_TRADE_HISTORY_SOCKET"; // added by devang parekh for when change pair

// Actions Types For Active Order List Actions For Get Active Order By Tejas Date : 14/9/2018
export const GET_ACTIVE_OPEN_ORDER_LIST = "GET_ACTIVE_OPEN_ORDER_LIST";
export const GET_ACTIVE_OPEN_ORDER_LIST_SUCCESS = "GET_ACTIVE_OPEN_ORDER_LIST_SUCCESS";
export const GET_ACTIVE_OPEN_ORDER_LIST_FAILURE = "GET_ACTIVE_OPEN_ORDER_LIST_FAILURE";

// Actions Types For Active Order List Actions For Get Active Order By Tejas Date : 14/9/2018
export const GET_ACTIVE_OPEN_MY_ORDER_LIST = "GET_ACTIVE_OPEN_MY_ORDER_LIST";
export const GET_ACTIVE_OPEN_MY_ORDER_LIST_SUCCESS = "GET_ACTIVE_OPEN_MY_ORDER_LIST_SUCCESS";
export const GET_ACTIVE_OPEN_MY_ORDER_LIST_FAILURE = "GET_ACTIVE_OPEN_MY_ORDER_LIST_FAILURE";

// Actions Types For Market Cap List Actions For Get Current Market Cap By Tejas Date : 14/9/2018
export const GET_MARKET_CAP_LIST = "GET_MARKET_CAP_LIST";
export const GET_MARKET_CAP_LIST_SUCCESS = "GET_MARKET_CAP_LIST_SUCCESS";
export const GET_MARKET_CAP_LIST_FAILURE = "GET_MARKET_CAP_LIST_FAILURE";

// Actions Types For News Tickers Actions For Get Current Market Cap By Tejas Date : 14/9/2018
export const GET_NEWS_TICKER_LIST = "GET_NEWS_TICKER_LIST";
export const GET_NEWS_TICKER_LIST_SUCCESS = "GET_NEWS_TICKER_LIST_SUCCESS";
export const GET_NEWS_TICKER_LIST_FAILURE = "GET_NEWS_TICKER_LIST_FAILURE";

// Actions Types For Tickers Actions  By Tejas Date : 17/9/2018
export const GET_TICKERS_LIST = "GET_TICKERS_LIST";
export const GET_TICKERS_LIST_SUCCESS = "GET_TICKERS_LIST_SUCCESS";
export const GET_TICKERS_LIST_FAILURE = "GET_TICKERS_LIST_FAILURE";

// Actions Types For News Tickers Actions For Get Currency Detail By Tejas Date : 17/9/2018
export const GET_CURRENCY_LIST = "GET_CURRENCY_LIST";
export const GET_CURRENCY_LIST_SUCCESS = "GET_CURRENCY_LIST_SUCCESS";
export const GET_CURRENCY_LIST_FAILURE = "GET_CURRENCY_LIST_FAILURE";

// Actions Types For News Tickers Actions For Update Balance By Tejas
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAILURE = "UPDATE_BALANCE_FAILURE";

// Actions Types For Bulk Order By Tejas Date : 20/9/2018
export const DO_BULK_BUYER_ORDER = "DO_BULK_BUYER_ORDER";
export const DO_BULK_BUYER_ORDER_SUCCESS = "DO_BULK_BUYER_ORDER_SUCCESS";
export const DO_BULK_BUYER_ORDER_FAILURE = "DO_BULK_BUYER_ORDER_FAILURE";

// Actions Types For Bulk Order By Tejas Date : 20/9/2018
export const DO_BULK_SELLER_ORDER = "DO_BULK_SELLER_ORDER";
export const DO_BULK_SELLER_ORDER_SUCCESS = "DO_BULK_SELLER_ORDER_SUCCESS";
export const DO_BULK_SELLER_ORDER_FAILURE = "DO_BULK_SELLER_ORDER_FAILURE";

// Actions Types For Buy Order  By Tejas Date : 20/9/2018
export const DO_BUY_ORDER = "DO_BUY_ORDER";
export const DO_BUY_ORDER_SUCCESS = "DO_BUY_ORDER_SUCCESS";
export const DO_BUY_ORDER_FAILURE = "DO_BUY_ORDER_FAILURE";

// Actions Types For Sell Order  By Tejas Date : 20/9/2018
export const DO_SELL_ORDER = "DO_SELL_ORDER";
export const DO_SELL_ORDER_SUCCESS = "DO_SELL_ORDER_SUCCESS";
export const DO_SELL_ORDER_FAILURE = "DO_SELL_ORDER_FAILURE";

// Actions Types For Cancel Order  By Tejas Date : 21/9/2018
export const DO_CANCEL_ORDER = "DO_CANCEL_ORDER";
export const DO_CANCEL_ORDER_SUCCESS = "DO_CANCEL_ORDER_SUCCESS";
export const DO_CANCEL_ORDER_FAILURE = "DO_CANCEL_ORDER_FAILURE";

// list of action types for transaction history (devang parekh);
export const TRANSACTION_HISTORY = "TRANSACTION_HISTORY";
export const TRANSACTION_HISTORY_SUCCESS = "TRANSACTION_HISTORY_SUCCESS";
export const TRANSACTION_HISTORY_FAILURE = "TRANSACTION_HISTORY_FAILURE";
export const TRANSACTION_HISTORY_REFRESH = "TRANSACTION_HISTORY_REFRESH";
export const TRANSACTION_HISTORY_REFRESH_SUCCESS = "TRANSACTION_HISTORY_REFRESH_SUCCESS";

// list of action types for open orders (devang parekh);
export const OPEN_ORDERS = "OPEN_ORDERS";
export const OPEN_ORDERS_SUCCESS = "OPEN_ORDERS_SUCCESS";
export const OPEN_ORDERS_FAILURE = "OPEN_ORDERS_FAILURE";
export const OPEN_ORDERS_REFRESH = "OPEN_ORDERS_REFRESH";
export const OPEN_ORDERS_REFRESH_SUCCESS = "OPEN_ORDERS_REFRESH_SUCCESS";

// List Of Action types for GetChart Data (tejas)
export const GET_CHART_DATA = "GET_CHART_DATA";
export const GET_CHART_DATA_SUCCESS = "GET_CHART_DATA_SUCCESS";
export const GET_CHART_DATA_FAILURE = "GET_CHART_DATA_FAILURE";

// List Of Action types for Faq (Kushal)
export const GET_FAQ = "GET_FAQ";
export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";
export const GET_FAQ_FAILURE = "GET_FAQ_FAILURE";

export const GET_FAQ_CATEGORIES = "GET_FAQ_CATEGORIES";
export const GET_FAQ_CATEGORIES_SUCCESS = "GET_FAQ_CATEGORIES_SUCCESS";
export const GET_FAQ_CATEGORIES_FAILURE = "GET_FAQ_CATEGORIES_FAILURE";

export const GET_FAQ_QUESTIONS = "GET_FAQ_QUESTIONS";
export const GET_FAQ_QUESTIONS_SUCCESS = "GET_FAQ_QUESTIONS_SUCCESS";
export const GET_FAQ_QUESTIONS_FAILURE = "GET_FAQ_QUESTIONS_FAILURE";

export const UPDATE_SEARCH_FAQ = "UPDATE_SEARCH_FAQ";
export const ON_SEARCH_FAQ = "ON_SEARCH_FAQ";
export const SHOW_FAQ_LOADING_INDICATOR = "SHOW_FAQ_LOADING_INDICATOR";
export const HIDE_FAQ_LOADING_INDICATOR = "HIDE_FAQ_LOADING_INDICATOR";

// List Of Action types for Contact Us (Kushal)
export const ADD_NEW_CONTACTUS = "ADD_NEW_CONTACTUS";
export const ADD_CONTACTUS_SUCCESS = "ADD_CONTACTUS_SUCCESS";
export const ADD_CONTACTUS_FAILURE = "ADD_CONTACTUS_FAILURE";
export const SHOW_CONTACTUS_LOADING_INDICATOR = "SHOW_CONTACTUS_LOADING_INDICATOR";

// List Of Action types for News (Kushal)
export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";
export const GET_NEWSDETAIL = "GET_NEWSDETAIL";
export const GET_NEWSDETAIL_SUCCESS = "GET_NEWSDETAIL_SUCCESS";
export const GET_NEWSDETAIL_FAILURE = "GET_NEWSDETAIL_FAILURE";

// List Of Action types for Announcement (Kushal)
export const GET_ANNOUCEMENT = "GET_ANNOUCEMENT";
export const GET_ANNOUCEMENT_SUCCESS = "GET_ANNOUCEMENT_SUCCESS";
export const GET_ANNOUCEMENT_FAILURE = "GET_ANNOUCEMENT_FAILURE";

// List Of Action types for API (Kushal)
export const GET_API = "GET_API";
export const GET_API_SUCCESS = "GET_API_SUCCESS";
export const GET_API_FAILURE = "GET_API_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 22-09-2018
    File Comment : convert token action constants
*/
// get slab list
export const GET_CTHISTORY = "GET_CTHISTORY";
export const GET_CTHISTORY_SUCCESS = "GET_CTHISTORY_SUCCESS";
export const GET_CTHISTORY_FAILURE = "GET_CTHISTORY_FAILURE";

//convert token actions
export const GET_CTINFO = "GET_CTINFO";
export const GET_CTINFO_SUCCESS = "GET_CTINFO_SUCCESS";
export const GET_CTINFO_FAILURE = "GET_CTINFO_FAILURE";

//convert token actions
export const SUBMIT_CTREQUEST = "SUBMIT_CTREQUEST";
export const SUBMIT_CTREQUEST_SUCCESS = "SUBMIT_CTREQUEST_SUCCESS";
export const SUBMIT_CTREQUEST_FAILURE = "SUBMIT_CTREQUEST_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 13-09-2018
    Comment : App Redux Action Types for deposit
*/
// Deposit History
export const GET_DEPOSIT_HISTORY = "GET_DEPOSIT_HISTORY";
export const GET_DEPOSIT_HISTORY_SUCCESS = "GET_DEPOSIT_HISTORY_SUCCESS";
export const GET_DEPOSIT_HISTORY_FAILURE = "GET_DEPOSIT_HISTORY_FAILURE";

//Get Balance action for deposit
export const GET_AD_CURRENCY = "GET_AD_CURRENCY";
export const GET_AD_CURRENCY_SUCCESS = "GET_AD_CURRENCY_SUCCESS";
export const GET_AD_CURRENCY_FAILURE = "GET_AD_CURRENCY_FAILURE";
//Deposit Address Generation
export const GET_AD_WALLETS = "GET_AD_WALLETS";
export const GET_AD_WALLETS_SUCCESS = "GET_AD_WALLETS_SUCCESS";
export const GET_AD_WALLETS_FAILURE = "GET_AD_WALLETS_FAILURE";
//GET BALANCE FOR WITHDRAW
export const GET_AD_BALANCE = "GET_AD_BALANCE";
export const GET_AD_BALANCE_SUCCESS = "GET_AD_BALANCE_SUCCESS";
export const GET_AD_BALANCE_FAILURE = "GET_AD_BALANCE_FAILURE";
//GET DEFAULT ADDRESS OF WALLET
export const GET_DEFAULT_ADD = "GET_DEFAULT_ADD";
export const GET_DEFAULT_ADD_SUCCESS = "GET_DEFAULT_ADD_SUCCESS";
export const GET_DEFAULT_ADD_FAILURE = "GET_DEFAULT_ADD_FAILURE";
// GENERATE ADDRESS
export const GENERATE_ADDRESS = "GENERATE_ADDRESS";
export const GENERATE_ADDRESS_SUCCESS = "GENERATE_ADDRESS_SUCCESS";
export const GENERATE_ADDRESS_FAILURE = "GENERATE_ADDRESS_FAILURE";
// update ltc address converted hash
export const UPDATE_P2SH_ADDRESS = "UPDATE_P2SH_ADDRESS";
export const UPDATE_P2SH_ADDRESS_SUCCESS = "UPDATE_P2SH_ADDRESS_SUCCESS";
export const UPDATE_P2SH_ADDRESS_FAILURE = "UPDATE_P2SH_ADDRESS_FAILURE";

//Get Balance action for deposit
export const GET_BALANCE = "GET_BALANCE";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILURE = "GET_BALANCE_FAILURE";
// export const REFRESH_BALANCE = 'REFRESH_BALANCE';

/* 
    Developer : Nishant Vadgam
    Date : 25-09-2018
    File Comment : Constant for LImists control actions
*/

export const GET_LC_WALLETS = "GET_LC_WALLETS";
export const GET_LC_WALLETS_SUCCESS = "GET_LC_WALLETS_SUCCESS";
export const GET_LC_WALLETS_FAILURE = "GET_LC_WALLETS_FAILURE";

//get details from server
export const GET_LIMITINFO = "GET_LIMITINFO";
export const GET_LIMITINFO_SUCCES = "GET_LIMITINFO_SUCCESS";
export const GET_LIMITINFO_FAILURE = "GET_LIMITINFO_FAILURE";

//post details to server
export const POST_LIMITINFO = "POST_LIMITINFO";
export const POST_LIMITINFO_SUCCESS = "POST_LIMITINFO_SUCCESS";
export const POST_LIMITINFO_FAILURE = "POST_LIMITINFO_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 21-09-2018
    File Comment : list of constant for token staking actions
*/
// get plan slab list...
export const GET_SLABLIST = "GET_SLABLIST";
export const GET_SLABLIST_SUCCESS = "GET_SLABLIST_SUCCESS";
export const GET_SLABLIST_FAILURE = "GET_SLABLIST_FAILURE";

// get pre confirmation
export const PRECONFIRMATIONDETAILS = "PRECONFIRMATIONDETAILS";
export const PRECONFIRMATIONDETAILS_SUCCESS = "PRECONFIRMATIONDETAILS_SUCCESS";
export const PRECONFIRMATIONDETAILS_FAILURE = "PRECONFIRMATIONDETAILS_FAILURE";

// stack request
export const STAKREQUEST = "STAKREQUEST";
export const STAKREQUEST_SUCCESS = "STAKREQUEST_SUCCESS";
export const STAKREQUEST_FAILURE = "STAKREQUEST_FAILURE";

// unstak pre confirmation
export const UNSTAKPRECONFIRMATION = "UNSTAKPRECONFIRMATION";
export const UNSTAKPRECONFIRMATION_SUCCESS = "UNSTAKPRECONFIRMATION_SUCCESS";
export const UNSTAKPRECONFIRMATION_FAILURE = "UNSTAKPRECONFIRMATION_FAILURE";

// unstack request
export const UNSTAKREQUEST = "UNSTAKREQUEST";
export const UNSTAKREQUEST_SUCCESS = "UNSTAKREQUEST_SUCCESS";
export const UNSTAKREQUEST_FAILURE = "UNSTAKREQUEST_FAILURE";

//get wallet type list
export const GETWALLETTYPELIST = "GETWALLETTYPELIST";
export const GETWALLETTYPELIST_SUCCESS = "GETWALLETTYPELIST_SUCCESS";
export const GETWALLETTYPELIST_FAILURE = "GETWALLETTYPELIST_FAILURE";

// get staking history
export const GET_STAKHISTORY = "GET_STAKHISTORY";
export const GET_STAKHISTORY_SUCCESS = "GET_STAKHISTORY_SUCCESS";
export const GET_STAKHISTORY_FAILURE = "GET_STAKHISTORY_FAILURE";
//===================TransferIn Actions======================================
export const GET_INTERNALTRANSFER_HISTORY = "GET_INTERNALTRANSFER_HISTORY";
export const GET_INTERNALTRANSFER_HISTORY_SUCCESS = "GET_INTERNALTRANSFER_HISTORY_SUCCESS";
export const GET_INTERNALTRANSFER_HISTORY_FAILURE = "GET_INTERNALTRANSFER_HISTORY_FAILURE";

//===================TransferOut Actions======================================
export const GET_EXTERNALTRANSFER_HISTORY = "GET_EXTERNALTRANSFER_HISTORY";
export const GET_EXTERNALTRANSFER_HISTORY_SUCCESS = "GET_EXTERNALTRANSFERT_HISTORY_SUCCESS";
export const GET_EXTERNALTRANSFER_HISTORY_FAILURE = "GET_EXTERNALTRANSFER_HISTORY_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 13-09-2018
    Comment :  App Redux Action Types for Withdraw 
*/
//Get Withdraw History
export const GET_WITHDRAW_HISTORY = "GET_WITHDRAW_HISTORY";
export const GET_WITHDRAW_HISTORY_SUCCESS = "GET_WITHDRAW_HISTORY_SUCCESS";
export const GET_WITHDRAW_HISTORY_FAILURE = "GET_WITHDRAW_HISTORY_FAILURE";
//Get Balance action for deposit
export const GET_WD_CURRENCY = "GET_WD_CURRENCY";
export const GET_WD_CURRENCY_SUCCESS = "GET_WD_CURRENCY_SUCCESS";
export const GET_WD_CURRENCY_FAILURE = "GET_WD_CURRENCY_FAILURE";
//GET WALLETS FOR WITHDRAW
export const GET_WD_WALLETS = "GET_WD_WALLETS";
export const GET_WD_WALLETS_SUCCESS = "GET_WD_WALLETS_SUCCESS";
export const GET_WD_WALLETS_FAILURE = "GET_WD_WALLETS_FAILURE";
//GET BALANCE FOR WITHDRAW
export const GET_WD_BALANCE = "GET_WD_BALANCE";
export const GET_WD_BALANCE_SUCCESS = "GET_WD_BALANCE_SUCCESS";
export const GET_WD_BALANCE_FAILURE = "GET_WD_BALANCE_FAILURE";
//GET FEE AND LIMIT FOR WITHDRAW
export const GET_FEEANDLIMIT = "GET_FEEANDLIMIT";
export const GET_FEEANDLIMIT_SUCCESS = "GET_FEEANDLIMIT_SUCCESS";
export const GET_FEEANDLIMIT_FAILURE = "GET_FEEANDLIMIT_FAILURE";
// withdraw request
export const DO_WITHDRAW = "DO_WITHDRAW";
export const DO_WITHDRAW_SUCCESS = "DO_WITHDRAW_SUCCESS";
export const DO_WITHDRAW_FAILURE = "DO_WITHDRAW_FAILURE";
// list address by walletid
export const ADDRESSBYWALLETID = "ADDRESSBYWALLETID";
export const ADDRESSBYWALLETID_SUCCESS = "ADDRESSBYWALLETID_SUCCESS";
export const ADDRESSBYWALLETID_FAILURE = "ADDRESSBYWALLETID_FAILURE";

// added by devang parekh for close socket connection
export const CLOSE_SOCKET_CONNECTION = "CLOSE_SOCKET_CONNECTION";

/* Decentralize Address Generation Constants - added by nishant */
// get currency list
export const GET_CURRENCY = "GET_CURRENCY";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAILURE = "GET_CURRENCY_FAILURE";

/// added By Tejas For Get Current Price
export const GET_CURRENT_PRICE = "GET_CURRENT_PRICE";
export const GET_CURRENT_PRICELIST_SUCCESS = "GET_CURRENT_PRICE_SUCCESS";
export const GET_CURRENT_PRICE_FAILURE = "GET_CURRENT_PRICE_FAILURE";

// post data to generate address
export const DECENT_ADDRESS_GENERATION = "DECENT_ADDRESS_GENERATION";
export const DECENT_ADDRESS_GEN_SUCCESS = "DECENT_ADDRESS_GEN_SUCCESS";
export const DECENT_ADDRESS_GEN_FAILURE = "DECENT_ADDRESS_GEN_FAILURE";

/* Address Whitelist */
// GET COIN LIST
export const GET_COIN_LIST = "GET_COIN_LIST";
export const GET_COIN_LIST_SUCCESS = "GET_COIN_LIST_SUCCESS";
export const GET_COIN_LIST_FAILURE = "GET_COIN_LIST_FAILURE";
// GET GLOBAL PREFERENCE
export const GET_PREFERENCE = "GET_PREFERENCE";
export const GET_PREFERENCE_SUCCESS = "GET_PREFERENCE_SUCCESS";
export const GET_PREFERENCE_FAILURE = "GET_PREFERENCE_FAILURE";
// SET GLOBAL PREFERENCE
export const SET_PREFERENCE = "SET_PREFERENCE";
export const SET_PREFERENCE_SUCCESS = "SET_PREFERENCE_SUCCESS";
export const SET_PREFERENCE_FAILURE = "SET_PREFERENCE_FAILURE";
// add
export const SUBMIT_WITHDRAWALADDRESSES = "SUBMIT_WITHDRAWALADDRESSES";
export const SUBMIT_WITHDRAWALADDRESSES_SUCCESS = "SUBMIT_WITHDRAWALADDRESSES_SUCCESS";
export const SUBMIT_WITHDRAWALADDRESSES_FAIL = "SUBMIT_WITHDRAWALADDRESSES_FAIL";
// list
export const FETCH_WITHDRAWALADDRESS = "FETCH_WITHDRAWALADDRESS";
export const FETCH_WITHDRAWALADDRESS_SUCCESS = "FETCH_WITHDRAWALADDRESS_SUCCESS";
export const FETCH_WITHDRAWALADDRESS_FAIL = "FETCH_WITHDRAWALADDRESS_FAIL";
// add to whitelist 
export const ADDTO_WHITELIST = "ADDTO_WHITELIST";
export const ADDTO_WHITELIST_SUCCESS = "ADDTO_WHITELIST_SUCCESS";
export const ADDTO_WHITELIST_FAILURE = "ADDTO_WHITELIST_FAILURE";
// remove form whitelis
export const REMOVE_WHITELIST = "REMOVE_WHITELIST";
export const REMOVE_WHITELIST_SUCCESS = "REMOVE_WHITELIST_SUCCESS";
export const REMOVE_WHITELIST_FAILURE = "REMOVE_WHITELIST_FAILURE";
// delete from whitelis;
export const DELETE_ADDRESSES = "DELETE_ADDRESSES";
export const DELETE_ADDRESSES_SUCCESS = "DELETE_ADDRESSES_SUCCESS";
export const DELETE_ADDRESSES_FAILURE = "DELETE_ADDRESSES_FAILURE";

// Added By Tejas For Transaction Charge report
export const GET_TRANSACTION_CHARGE = "GET_TRANSACTION_CHARGE";
export const GET_TRANSACTION_CHARGE_SUCCESS = "GET_TRANSACTION_CHARGE_SUCCESS";
export const GET_TRANSACTION_CHARGE_FAILURE = "GET_TRANSACTION_CHARGE_FAILURE";

// list of action types for Trading Ledger (Nirmit);
export const TRADING_LEDGER = "TRADING_LEDGER";
export const TRADING_LEDGER_SUCCESS = "TRADING_LEDGER_SUCCESS";
export const TRADING_LEDGER_FAILURE = "TRADING_LEDGER_FAILURE";
export const TRADING_LEDGER_REFRESH = "TRADING_LEDGER_REFRESH";
export const TRADING_LEDGER_REFRESH_SUCCESS = "TRADING_LEDGER_REFRESH_SUCCESS";

/* 
    Developer : Nishant Vadgama
    Date : 25-10-2018
    Constant for fund balance page
*/
// get total balance of all wallets
export const GET_ALL_BALANCE = "GET_ALL_BALANCE";
export const GET_ALL_BALANCE_SUCCESS = "GET_ALL_BALANCE_SUCCESS";
export const GET_ALL_BALANCE_FAILURE = "GET_ALL_BALANCE_FAILURE";
// get seprated balance by coin
export const GET_WALLETBALANCE = "GET_WALLETBALANCE";
export const GET_WALLETBALANCE_SUCCESS = "GET_WALLETBALANCE_SUCCESS";
export const GET_WALLETBALANCE_FAILURE = "GET_WALLETBALANCE_FAILURE";

//OutGoing Transaction
export const GET_OUTGOINGTRANSACTION_REPORT = "GET_OUTGOINGTRANSACTION_REPORT";
export const GET_OUTGOINGTRANSACTION_REPORT_SUCCESS = "GET_OUTGOINGTRANSACTION_REPORT_SUCCESS";
export const GET_OUTGOINGTRANSACTION_REPORT_FAILURE = "GET_OUTGOINGTRANSACTION_REPORT_FAILURE";

//Incoming Transactions
export const GET_INCOMINGTRANSACTONS_REPORT = "GET_INCOMINGTRANSACTONS_REPORT";
export const GET_INCOMINGTRANSACTONS_REPORT_SUCCESS = "GET_INCOMINGTRANSACTONS_REPORT_SUCCESS";
export const GET_INCOMINGTRANSACTONS_REPORT_FAILURE = "GET_INCOMINGTRANSACTONS_REPORT_FAILURE";

// Added By Tejas
// list of action types for My Ledger (Nirmit);
export const MY_LEDGER = "MY_LEDGER";
export const MY_LEDGER_SUCCESS = "MY_LEDGER_SUCCESS";
export const MY_LEDGER_FAILURE = "MY_LEDGER_FAILURE";

//Added By Kushal
// list of Action Type for Coinlist
export const GET_COINLIST = "GET_COINLIST";
export const GET_COINLIST_SUCCESS = "GET_COINLIST_SUCCESS";
export const GET_COINLIST_FAILURE = "GET_COINLIST_FAILURE";

// code added by devang parekh for favourite pair process
export const GET_FAVOURITE_PAIR_LIST = "GET_FAVOURITE_PAIR_LIST";
export const GET_FAVOURITE_PAIR_LIST_SUCCESS = "GET_FAVOURITE_PAIR_LIST_SUCCESS";
export const GET_FAVOURITE_PAIR_LIST_FAILED = "GET_FAVOURITE_PAIR_LIST_FAILED";
export const ADD_PAIR_TO_FAVOURITE_PAIR = "ADD_PAIR_TO_FAVOURITE_PAIR";
export const ADD_PAIR_TO_FAVOURITE_PAIR_SUCCESS = "ADD_PAIR_TO_FAVOURITE_PAIR_SUCCESS";
export const ADD_PAIR_TO_FAVOURITE_PAIR_FAILED = "ADD_PAIR_TO_FAVOURITE_PAIR_FAILED";
export const REMOVE_PAIR_FROM_FAVOURITE_PAIR = "REMOVE_PAIR_FROM_FAVOURITE_PAIR";
export const REMOVE_PAIR_FROM_FAVOURITE_PAIR_SUCCESS = "REMOVE_PAIR_FROM_FAVOURITE_PAIR_SUCCESS";
export const REMOVE_PAIR_FROM_FAVOURITE_PAIR_FAILED = "REMOVE_PAIR_FROM_FAVOURITE_PAIR_FAILED";

/* Withdrawal 2FA - added by Nishant */
export const WITHDRAWA2FAAUTH = "WITHDRAWA2FAAUTH";
export const WITHDRAWA2FAAUTH_SUCCESS = "WITHDRAWA2FAAUTH_SUCCESS";
export const WITHDRAWA2FAAUTH_FAILURE = "WITHDRAWA2FAAUTH_FAILURE";

/* Withdrawal Confirmation - added by Nishant */
export const WITHDRAWCONFRIMATION = "WITHDRAWCONFRIMATION";
export const WITHDRAWCONFRIMATION_SUCCESS = "WITHDRAWCONFRIMATION_SUCCESS";
export const WITHDRAWCONFRIMATION_FAILURE = "WITHDRAWCONFRIMATION_FAILURE";

/* resend mail confirmation */
export const RESENDMAIL = "RESENDMAIL";
export const RESENDMAIL_SUCCESS = "RESENDMAIL_SUCCESS";
export const RESENDMAIL_FAILURE = "RESENDMAIL_FAILURE";

/* wallet sharing - added by Nishant */
export const LISTALLWALLETS = "LISTALLWALLETS";
export const LISTALLWALLETS_SUCCESS = "LISTALLWALLETS_SUCCESS";
export const LISTALLWALLETS_FAILURE = "LISTALLWALLETS_FAILURE";
/* wallet user list - added by Nishant */
export const LISTWALLETUSERS = "LISTWALLETUSERS";
export const LISTWALLETUSERS_SUCCESS = "LISTWALLETUSERS_SUCCESS";
export const LISTWALLETUSERS_FAILURE = "LISTWALLETUSERS_FAILURE";
/* add wallet user - added by Nishant */
export const ADDWALLETUSER = "ADDWALLETUSER";
export const ADDWALLETUSER_SUCCESS = "ADDWALLETUSER_SUCCESS";
export const ADDWALLETUSER_FAILURE = "ADDWALLETUSER_FAILURE";
/* list wallet request - added by Nishant */
export const LISTWALLETREQUEST = "LISTWALLETREQUEST";
export const LISTWALLETREQUEST_SUCCESS = "LISTWALLETREQUEST_SUCCESS";
export const LISTWALLETREQUEST_FAILURE = "LISTWALLETREQUEST_FAILURE";
/* add wallet user - added by Nishant */
export const ACCEPTREJECTWALLETREQUEST = "ACCEPTREJECTWALLETREQUEST";
export const ACCEPTREJECTWALLETREQUEST_SUCCESS = "ACCEPTREJECTWALLETREQUEST_SUCCESS";
export const ACCEPTREJECTWALLETREQUEST_FAILURE = "ACCEPTREJECTWALLETREQUEST_FAILURE";

/* ========================= Social Profile ====================================== */
/* ==================== KEVIN SECTION ===================== */
//Edit Leader Configuration - 19/12/2018
export const EDIT_LEADER_CONFIG = "EDIT_LEADER_CONFIG";
export const EDIT_LEADER_CONFIG_SUCCESS = "EDIT_LEADER_CONFIG_SUCCESS";
export const EDIT_LEADER_CONFIG_FAILURE = "EDIT_LEADER_CONFIG_FAILURE";

//Edit Follower Configuration - 19/12/2018
export const EDIT_FOLLOWER_CONFIG = "EDIT_FOLLOWER_CONFIG";
export const EDIT_FOLLOWER_CONFIG_SUCCESS = "EDIT_FOLLOWER_CONFIG_SUCCESS";
export const EDIT_FOLLOWER_CONFIG_FAILURE = "EDIT_FOLLOWER_CONFIG_FAILURE";

//Get Follower Configuration (Salim Deraiya) - 27/12/2018
export const GET_FOLLOWER_CONFIG = "GET_FOLLOWER_CONFIG";
export const GET_FOLLOWER_CONFIG_SUCCESS = "GET_FOLLOWER_CONFIG_SUCCESS";
export const GET_FOLLOWER_CONFIG_FAILURE = "GET_FOLLOWER_CONFIG_FAILURE";

//Get Leader Configuration (Salim Deraiya) - 27/12/2018
export const GET_LEADER_CONFIG = "GET_LEADER_CONFIG";
export const GET_LEADER_CONFIG_SUCCESS = "GET_LEADER_CONFIG_SUCCESS";
export const GET_LEADER_CONFIG_FAILURE = "GET_LEADER_CONFIG_FAILURE";

//Get Social Profile Subscription (Salim Deraiya) - 24/12/2018
export const GET_SOCIAL_PROFILE_SUBSCRIPTION = "GET_SOCIAL_PROFILE_SUBSCRIPTION";
export const GET_SOCIAL_PROFILE_SUBSCRIPTION_SUCCESS = "GET_SOCIAL_PROFILE_SUBSCRIPTION_SUCCESS";
export const GET_SOCIAL_PROFILE_SUBSCRIPTION_FAILURE = "GET_SOCIAL_PROFILE_SUBSCRIPTION_FAILURE";

//Social Profile Subscribe (Salim Deraiya) - 24/12/2018
export const SOCIAL_PROFILE_SUBSCRIBE = "SOCIAL_PROFILE_SUBSCRIBE";
export const SOCIAL_PROFILE_SUBSCRIBE_SUCCESS = "SOCIAL_PROFILE_SUBSCRIBE_SUCCESS";
export const SOCIAL_PROFILE_SUBSCRIBE_FAILURE = "SOCIAL_PROFILE_SUBSCRIBE_FAILURE";

//Social Profile UnSubscribe (Salim Deraiya) - 24/12/2018
export const SOCIAL_PROFILE_UNSUBSCRIBE = "SOCIAL_PROFILE_UNSUBSCRIBE";
export const SOCIAL_PROFILE_UNSUBSCRIBE_SUCCESS = "SOCIAL_PROFILE_UNSUBSCRIBE_SUCCESS";
export const SOCIAL_PROFILE_UNSUBSCRIBE_FAILURE = "SOCIAL_PROFILE_UNSUBSCRIBE_FAILURE";

//Get Leader list (Salim Deraiya) - 16/01/2019
export const GET_LEADER_LIST = "GET_LEADER_LIST";
export const GET_LEADER_LIST_SUCCESS = "GET_LEADER_LIST_SUCCESS";
export const GET_LEADER_LIST_FAILURE = "GET_LEADER_LIST_FAILURE";

//Get Leader Follow By ID (Salim Deraiya) - 17/01/2019
export const GET_LEADER_FOLLOW_BY_ID = "GET_LEADER_FOLLOW_BY_ID";
export const GET_LEADER_FOLLOW_BY_ID_SUCCESS = "GET_LEADER_FOLLOW_BY_ID_SUCCESS";
export const GET_LEADER_FOLLOW_BY_ID_FAILURE = "GET_LEADER_FOLLOW_BY_ID_FAILURE";

//Get Unfollow Leader (Salim Deraiya) - 17/01/2019
export const UNFOLLOW_LEADER = "UNFOLLOW_LEADER";
export const UNFOLLOW_LEADER_SUCCESS = "UNFOLLOW_LEADER_SUCCESS";
export const UNFOLLOW_LEADER_FAILURE = "UNFOLLOW_LEADER_FAILURE";

//Get Follower list (Salim Deraiya) - 22/01/2019
export const GET_FOLLOWER_LIST = "GET_FOLLOWER_LIST";
export const GET_FOLLOWER_LIST_SUCCESS = "GET_FOLLOWER_LIST_SUCCESS";
export const GET_FOLLOWER_LIST_FAILURE = "GET_FOLLOWER_LIST_FAILURE";

//Get Social Trading Policy Configuration - 24/12/2018
export const GET_SOCIAL_TRADING_POLICY = "GET_SOCIAL_TRADING_POLICY";
export const GET_SOCIAL_TRADING_POLICY_SUCCESS = "GET_SOCIAL_TRADING_POLICY_SUCCESS";
export const GET_SOCIAL_TRADING_POLICY_FAILURE = "GET_SOCIAL_TRADING_POLICY_FAILURE";

//Get Historical Performance (Salim Deraiya) - 23/01/2019
export const GET_HISTORICAL_PERFORMANCE_CHART_DATA = "GET_HISTORICAL_PERFORMANCE_CHART_DATA";
export const GET_HISTORICAL_PERFORMANCE_CHART_DATA_SUCCESS = "GET_HISTORICAL_PERFORMANCE_CHART_DATA_SUCCESS";
export const GET_HISTORICAL_PERFORMANCE_CHART_DATA_FAILURE = "GET_HISTORICAL_PERFORMANCE_CHART_DATA_FAILURE";


//Add Watchlist Group (Salim Deraiya) - 28/01/2019
export const ADD_WATCHLIST_GROUP = "ADD_WATCHLIST_GROUP";
export const ADD_WATCHLIST_GROUP_SUCCESS = "ADD_WATCHLIST_GROUP_SUCCESS";
export const ADD_WATCHLIST_GROUP_FAILURE = "ADD_WATCHLIST_GROUP_FAILURE";

//Add Watchlist (Salim Deraiya) - 28/01/2019
export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const ADD_WATCHLIST_SUCCESS = "ADD_WATCHLIST_SUCCESS";
export const ADD_WATCHLIST_FAILURE = "ADD_WATCHLIST_FAILURE";

//Remove Watchlist (Salim Deraiya) - 28/01/2019
export const REMOVE_WATCHLIST = "REMOVE_WATCHLIST";
export const REMOVE_WATCHLIST_SUCCESS = "REMOVE_WATCHLIST_SUCCESS";
export const REMOVE_WATCHLIST_FAILURE = "REMOVE_WATCHLIST_FAILURE";

//Get Watchlist (Salim Deraiya) - 28/01/2019
export const GET_WATCHLIST = "GET_WATCHLIST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAILURE = "GET_WATCHLIST_FAILURE";

//Get Leader watchlist (Salim Deraiya) - 28/01/2019
export const GET_LEADER_WATCH_LIST = "GET_LEADER_WATCH_LIST";
export const GET_LEADER_WATCH_LIST_SUCCESS = "GET_LEADER_WATCH_LIST_SUCCESS";
export const GET_LEADER_WATCH_LIST_FAILURE = "GET_LEADER_WATCH_LIST_FAILURE";

//Get Leader Portfolio List (Salim Deraiya) - 29/01/2019
export const GET_LEADER_PORTFOLIO_LIST = "GET_LEADER_PORTFOLIO_LIST";
export const GET_LEADER_PORTFOLIO_LIST_SUCCESS = "GET_LEADER_PORTFOLIO_LIST_SUCCESS";
export const GET_LEADER_PORTFOLIO_LIST_FAILURE = "GET_LEADER_PORTFOLIO_LIST_FAILURE";

//Get Top Gainer List (Salim Deraiya) - 31/01/2019
export const GET_TOP_GAINER_LIST = "GET_TOP_GAINER_LIST";
export const GET_TOP_GAINER_LIST_SUCCESS = "GET_TOP_GAINER_LIST_SUCCESS";
export const GET_TOP_GAINER_LIST_FAILURE = "GET_TOP_GAINER_LIST_FAILURE";

//Get Top Looser List (Salim Deraiya) - 31/01/2019
export const GET_TOP_LOOSER_LIST = "GET_TOP_LOOSER_LIST";
export const GET_TOP_LOOSER_LIST_SUCCESS = "GET_TOP_LOOSER_LIST_SUCCESS";
export const GET_TOP_LOOSER_LIST_FAILURE = "GET_TOP_LOOSER_LIST_FAILURE";

//Get Top Leader List (Salim Deraiya) - 31/01/2019
export const GET_TOP_LEADER_LIST = "GET_TOP_LEADER_LIST";
export const GET_TOP_LEADER_LIST_SUCCESS = "GET_TOP_LEADER_LIST_SUCCESS";
export const GET_TOP_LEADER_LIST_FAILURE = "GET_TOP_LEADER_LIST_FAILURE";

//Get Leader Board List (Salim Deraiya) - 07/02/2019
export const GET_LEADER_BOARD_LIST = "GET_LEADER_BOARD_LIST";
export const GET_LEADER_BOARD_LIST_SUCCESS = "GET_LEADER_BOARD_LIST_SUCCESS";
export const GET_LEADER_BOARD_LIST_FAILURE = "GET_LEADER_BOARD_LIST_FAILURE";

// added by Salim 11/02/2019 for 
//Affiliate Signup
export const AFFILIATE_SIGNUP = "AFFILIATE_SIGNUP";
export const AFFILIATE_SIGNUP_SUCCESS = "AFFILIATE_SIGNUP_SUCCESS";
export const AFFILIATE_SIGNUP_FAILURE = "AFFILIATE_SIGNUP_FAILURE";

//Affiliate Resend Confirmation Link
export const AFFILIATE_RESEND_CONFIRMATION_LINK = "AFFILIATE_RESEND_CONFIRMATION_LINK";
export const AFFILIATE_RESEND_CONFIRMATION_LINK_SUCCESS = "AFFILIATE_RESEND_CONFIRMATION_LINK_SUCCESS";
export const AFFILIATE_RESEND_CONFIRMATION_LINK_FAILURE = "AFFILIATE_RESEND_CONFIRMATION_LINK_FAILURE";

//Affiliate Confirmation Link
export const AFFILIATE_CONFIRMATION_LINK = "AFFILIATE_CONFIRMATION_LINK";
export const AFFILIATE_CONFIRMATION_LINK_SUCCESS = "AFFILIATE_CONFIRMATION_LINK_SUCCESS";
export const AFFILIATE_CONFIRMATION_LINK_FAILURE = "AFFILIATE_CONFIRMATION_LINK_FAILURE";

//Get Affiliate Signup Commission
export const GET_AFFILIATE_COMMISSION_PATTERN = "GET_AFFILIATE_COMMISSION_PATTERN";
export const GET_AFFILIATE_COMMISSION_PATTERN_SUCCESS = "GET_AFFILIATE_COMMISSION_PATTERN_SUCCESS";
export const GET_AFFILIATE_COMMISSION_PATTERN_FAILURE = "GET_AFFILIATE_COMMISSION_PATTERN_FAILURE";

//Added by Saloni Rathod
//For email promotion 
export const AFFILIATE_EMAIL_PROMO = "AFFILIATE_EMAIL_PROMO";
export const AFFILIATE_EMAIL_PROMO_SUCCESS = "AFFILIATE_EMAIL_PROMO_SUCCESS";
export const AFFILIATE_EMAIL_PROMO_FAILURE = "AFFILIATE_EMAIL_PROMO_FAILURE";

//fOR SMS PROMOTION
export const AFFILIATE_SMS_PROMO = "AFFILIATE_SMS_PROMO ";
export const AFFILIATE_SMS_PROMO_SUCCESS = "AFFILIATE_SMS_PROMO_SUCCESS";
export const AFFILIATE_SMS_PROMO_FAILURE = "AFFILIATE_SMS_PROMO_FAILURE";

//FOR SOCIAL SHARING
export const AFFILIATE_SOCIAL_SHARING_PROMO = "AFFILIATE_SOCIAL_SHARING_PROMO";
export const AFFILIATE_SOCIAL_SHARING_PROMO_SUCCESS = "AFFILIATE_SOCIAL_SHARING_PROMO_SUCCESS";
export const AFFILIATE_SOCIAL_SHARING_PROMO_FAILURE = "AFFILIATE_SOCIAL_SHARING_PROMO_FAILURE";

//Get Affiliate Promotion Link...
export const GET_AFFILIATE_PROMOTION_LINK = "GET_AFFILIATE_PROMOTION_LINK";
export const GET_AFFILIATE_PROMOTION_LINK_SUCCESS = "GET_AFFILIATE_PROMOTION_LINK_SUCCESS";
export const GET_AFFILIATE_PROMOTION_LINK_FAILURE = "GET_AFFILIATE_PROMOTION_LINK_FAILURE";

//For Affiliate Invite Friend Chart
export const AFFILIATE_INVITE_FRIEND_CHART = "AFFILIATE_INVITE_FRIEND_CHART";
export const AFFILIATE_INVITE_FRIEND_CHART_SUCCESS = "AFFILIATE_INVITE_FRIEND_CHART_SUCCESS";
export const AFFILIATE_INVITE_FRIEND_CHART_FAILURE = "AFFILIATE_INVITE_FRIEND_CHART_FAILURE";

//for export const affiliate Monthly average chart
export const AFFILIATE_MONTHLY_AVERAGE_COMMISSION_CHART = "AFFILIATE_MONTHLY_AVERAGE_COMMISSION_CHART";
export const AFFILIATE_MONTHLY_AVERAGE_COMMISSION_CHART_SUCCESS = "AFFILIATE_MONTHLY_AVERAGE_COMMISSION_CHART_SUCCESS";
export const AFFILIATE_MONTHLY_AVERAGE_COMMISSION_CHART_FAILURE = "AFFILIATE_MONTHLY_AVERAGE_COMMISSION_CHART_FAILURE";

//user Confirmation
export const USER_CONFIRMATION = "USER_CONFIRMATION";
export const USER_CONFIRMATION_SUCCESS = "USER_CONFIRMATION_SUCCESS";
export const USER_CONFIRMATION_FAILURE = "USER_CONFIRMATION_FAILURE";

//display affiliate Report
export const AFFILIATE_SIGNUP_REPORT = "AFFILIATE_SIGNUP_REPORT";
export const AFFILIATE_SIGNUP_REPORT_SUCCESS = "AFFILIATE_SIGNUP_REPORT_SUCCESS";
export const AFFILIATE_SIGNUP_REPORT_FAILURE = "AFFILIATE_SIGNUP_REPORT_FAILURE";

//display affiliate Commission Report
export const AFFILIATE_COMMISSION_REPORT = "AFFILIATE_COMMISSION_REPORT";
export const AFFILIATE_COMMISSION_REPORT_SUCCESS = "AFFILIATE_COMMISSION_REPORT_SUCCESS";
export const AFFILIATE_COMMISSION_REPORT_FAILURE = "AFFILIATE_COMMISSION_REPORT_FAILURE";

//display affiliate email sent report
export const AFFILIATE_EMAIL_SENT_REPORT = 'AFFILIATE_EMAIL_SENT_REPORT';
export const AFFILIATE_EMAIL_SENT_REPORT_SUCCESS = 'AFFILIATE_EMAIL_SENT_REPORT_SUCCESS';
export const AFFILIATE_EMAIL_SENT_REPORT_FAILURE = 'AFFILIATE_EMAIL_SENT_REPORT_FAILURE';

//display affiliate sms sent report
export const AFFILIATE_SMS_SENT_REPORT = 'AFFILIATE_SMS_SENT_REPORT';
export const AFFILIATE_SMS_SENT_REPORT_SUCCESS = 'AFFILIATE_SMS_SENT_REPORT_SUCCESS';
export const AFFILIATE_SMS_SENT_REPORT_FAILURE = 'AFFILIATE_SMS_SENT_REPORT_FAILURE';

//TO display affiliate all user report
export const AFFILIATE_ALL_USER = "AFFILIATE_ALL_USER";
export const AFFILIATE_ALL_USER_SUCCESS = "AFFILIATE_ALL_USER_SUCCESS";
export const AFFILIATE_ALL_USER_FAILURE = "AFFILIATE_ALL_USER_FAILURE";

//TO display affiliate all scheme type report
export const AFFILIATE_SCHEME_TYPE = "AFFILIATE_SCHEME_TYPE";
export const AFFILIATE_SCHEME_TYPE_SUCCESS = "AFFILIATE_SCHEME_TYPE_SUCCESS";
export const AFFILIATE_SCHEME_TYPE_FAILURE = "AFFILIATE_SCHEME_TYPE_FAILURE";

/************************ Code Ended By Saloni Rathod ********************/

//Added by Bharat Jograna
// For Affiliate Share On Facebook Report
export const AFFILIATE_SHARE_ON_FACEBOOK_REPORT = "AFFILIATE_SHARE_ON_FACEBOOK_REPORT";
export const AFFILIATE_SHARE_ON_FACEBOOK_REPORT_SUCCESS = "AFFILIATE_SHARE_ON_FACEBOOK_REPORT_SUCCESS";
export const AFFILIATE_SHARE_ON_FACEBOOK_REPORT_FAILURE = "AFFILIATE_SHARE_ON_FACEBOOK_REPORT_FAILURE";

// For Affiliate Share On Twitter Report
export const AFFILIATE_SHARE_ON_TWITTER_REPORT = "AFFILIATE_SHARE_ON_TWITTER_REPORT";
export const AFFILIATE_SHARE_ON_TWITTER_REPORT_SUCCESS = "AFFILIATE_SHARE_ON_TWITTER_REPORT_SUCCESS";
export const AFFILIATE_SHARE_ON_TWITTER_REPORT_FAILURE = "AFFILIATE_SHARE_ON_TWITTER_REPORT_FAILURE";

// For Affiliate Click On Link Report
export const AFFILIATE_CLICK_ON_LINK_REPORT = "AFFILIATE_CLICK_ON_LINK_REPORT";
export const AFFILIATE_CLICK_ON_LINK_REPORT_SUCCESS = "AFFILIATE_CLICK_ON_LINK_REPORT_SUCCESS";
export const AFFILIATE_CLICK_ON_LINK_REPORT_FAILURE = "AFFILIATE_CLICK_ON_LINK_REPORT_FAILURE";

// For Affiliate All Count Report
export const AFFILIATE_ALL_COUNT = "AFFILIATE_ALL_COUNT";
export const AFFILIATE_ALL_COUNT_SUCCESS = "AFFILIATE_ALL_COUNT_SUCCESS";
export const AFFILIATE_ALL_COUNT_FAILURE = "AFFILIATE_ALL_COUNT_FAILURE";

export const LIST_AFFILIATE_SCHEME_TYPE_MAPPING = "LIST_AFFILIATE_SCHEME_TYPE_MAPPING";
export const LIST_AFFILIATE_SCHEME_TYPE_MAPPING_SUCCESS = "LIST_AFFILIATE_SCHEME_TYPE_MAPPING_SUCCESS";
export const LIST_AFFILIATE_SCHEME_TYPE_MAPPING_FAILURE = "LIST_AFFILIATE_SCHEME_TYPE_MAPPING_FAILURE";

/************************ Code Ended By Bharat Jograna ********************/

// code added by devang parekh 26-12-2018 for handle coin slider module
export const COIN_SLIDER_LIST = "COIN_SLIDER_LIST";
export const COIN_SLIDER_LIST_SUCCESS = "COIN_SLIDER_LIST_SUCCESS";
export const COIN_SLIDER_LIST_FAILURE = "COIN_SLIDER_LIST_FAILURE";
//Language Configuration Get Language List from Node API added by Jayesh 11-12-2018
export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_FAILURE = "GET_LANGUAGES_FAILURE";

// Survey Form Added by Kushal 17-12-2018
export const GET_SURVEY = "GET_SURVEY";
export const GET_SURVEY_SUCCESS = "GET_SURVEY_SUCCESS";
export const GET_SURVEY_FAILURE = "GET_SURVEY_FAILURE";
export const ADD_SURVEYRESULT = "ADD_SURVEYRESULT";
export const ADD_SURVEYRESULT_SUCCESS = "ADD_SURVEYRESULT_SUCCESS";
export const ADD_SURVEYRESULT_FAILURE = "ADD_SURVEYRESULT_FAILURE";
export const GET_SURVEY_RESULTS_BY_ID = "GET_SURVEY_RESULTS_BY_ID";
export const GET_SURVEY_RESULTS_BY_ID_SUCCESS = "GET_SURVEY_RESULTS_BY_ID_SUCCESS";
export const GET_SURVEY_RESULTS_BY_ID_FAILURE = "GET_SURVEY_RESULTS_BY_ID_FAILURE";
//CMS Regions - Kushal 28-12-2018
export const GET_REGIONS = "GET_REGIONS";
export const GET_REGIONS_SUCCESS = "GET_REGIONS_SUCCESS";
export const GET_REGIONS_FAILURE = "GET_REGIONS_FAILURE";


//added by tejas for Top Gainers and Losers Data Date : 4-1-2019
export const GET_TOP_GAINERS_DATA = "GET_TOP_GAINERS_DATA";
export const GET_TOP_GAINERS_DATA_SUCCESS = "GET_TOP_GAINERS_DATA_SUCCESS";
export const GET_TOP_GAINERS_DATA_FAILURE = "GET_TOP_GAINERS_DATA_FAILURE";

export const GET_TOP_GAINERS_LOSERS_DATA = "GET_TOP_GAINERS_LOSERS_DATA";
export const GET_TOP_GAINERS_LOSERS_DATA_SUCCESS = "GET_TOP_GAINERS_LOSERS_DATA_SUCCESS";
export const GET_TOP_GAINERS_LOSERS_DATA_FAILURE = "GET_TOP_GAINERS_LOSERS_DATA_FAILURE";

export const GET_TOP_LOSERS_DATA = "GET_TOP_LOSERS_DATA";
export const GET_TOP_LOSERS_DATA_SUCCESS = "GET_TOP_LOSERS_DATA_SUCCESS";
export const GET_TOP_LOSERS_DATA_FAILURE = "GET_TOP_LOSERS_DATA_FAILURE";

// Actions Types For Pair List Actions For Get Pair  By Tejas 
export const GET_PAIR_LIST_DATA = "GET_PAIR_LIST_DATA";
export const GET_PAIR_LIST_DATA_SUCCESS = "GET_PAIR_LIST_DATA_SUCCESS";
export const GET_PAIR_LIST_DATA_FAILURE = "GET_PAIR_LIST_DATA_FAILURE";


//For Trade Summary Report
export const GET_TRADE_SUMMARY_DATA = "GET_TRADE_SUMMARY_DATA";
export const GET_TRADE_SUMMARY_DATA_SUCCESS = "GET_TRADE_SUMMARY_DATA_SUCCESS";
export const GET_TRADE_SUMMARY_DATA_FAILURE = "GET_TRADE_SUMMARY_DATA_FAILURE";

//CMS HelpCenter - Jayesh 09-01-2019
export const GET_HELPMANUALMODUALS = "GET_HELPMANUALMODUALS";
export const GET_HELPMANUALMODUALS_SUCCESS = "GET_HELPMANUALMODUALS_SUCCESS";
export const GET_HELPMANUALMODUALS_FAILURE = "GET_HELPMANUALMODUALS_FAILURE";
export const GET_HELPMANUALS_BY_ID = "GET_HELPMANUALS_BY_ID";
export const GET_HELPMANUALS_BY_ID_SUCCESS = "GET_HELPMANUALS_BY_ID_SUCCESS";
export const GET_HELPMANUALS_BY_ID_FAILURE = "GET_HELPMANUALS_BY_ID_FAILURE";

export const UPDATE_SEARCH_HELP = "UPDATE_SEARCH_HELP";
export const ON_SEARCH_HELP = "ON_SEARCH_HELP";
export const SHOW_HELP_LOADING_INDICATOR = "SHOW_HELP_LOADING_INDICATOR";
export const HIDE_HELP_LOADING_INDICATOR = "HIDE_HELP_LOADING_INDICATOR";


// List Of Action types for MArket Depth Dat (tejas) Date : 12/1/2019
export const GET_MARKET_DEPTH = "GET_MARKET_DEPTH";
export const GET_MARKET_DEPTH_SUCCESS = "GET_MARKET_DEPTH_SUCCESS";
export const GET_MARKET_DEPTH_FAILURE = "GET_MARKET_DEPTH_FAILURE";

//Added by dhara gajera 4/1/2019 for coin list field request
export const GET_COINLIST_REQUEST = "GET_COINLIST_REQUEST";
export const GET_COINLIST_REQUEST_SUCCESS = "GET_COINLIST_REQUEST_SUCCESS";
export const GET_COINLIST_REQUEST_FAILURE = "GET_COINLIST_REQUEST_FAILURE";

export const ADD_COINLIST_REQUEST = "ADD_COINLIST_REQUEST";
export const ADD_COINLIST_REQUEST_SUCCESS = "ADD_COINLIST_REQUEST_SUCCESS";
export const ADD_COINLIST_REQUEST_FAILURE = "ADD_COINLIST_REQUEST_FAILURE";

//Day/Night Mode Change Create By Sanjay

export const MODE_CHANGE = "MODE_CHANGE";
export const MODE_CHANGE_SUCCESS = "MODE_CHANGE_SUCCESS";
export const MODE_CHANGE_FAILURE = "MODE_CHANGE_FAILURE";

//Set New Password Create By Sanjay

export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
export const SET_NEW_PASSWORD_SUCCESS = "SET_NEW_PASSWORD_SUCCESS";
export const SET_NEW_PASSWORD_FAILURE = "SET_NEW_PASSWORD_FAILURE";

//added by dhara 28/1/2019
export const GET_COUNTRY = "GET_COUNTRY";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_FAILURE = "GET_COUNTRY_FAILURE";

// added by Tejas 6/2/2019 for Charge Type
export const GET_CHARGES_LIST = "GET_CHARGES_LIST";
export const GET_CHARGES_LIST_SUCCESS = "GET_CHARGES_LIST_SUCCESS";
export const GET_CHARGES_LIST_FAILURE = "GET_CHARGES_LIST_FAILURE";

// added by tejas for site token Report 11/2/2019
export const GET_SITE_TOKEN_REPORT_LIST = "GET_SITE_TOKEN_REPORT_LIST";
export const GET_SITE_TOKEN_REPORT_LIST_SUCCESS = "GET_SITE_TOKEN_REPORT_LIST_SUCCESS";
export const GET_SITE_TOKEN_REPORT_LIST_FAILURE = "GET_SITE_TOKEN_REPORT_LIST_FAILURE";

// Added By Tejas For Site Token Conversion
export const GET_SITE_TOKEN = "GET_SITE_TOKEN";
export const GET_SITE_TOKEN_SUCCESS = "GET_SITE_TOKEN_SUCCESS";
export const GET_SITE_TOKEN_FAILURE = "GET_SITE_TOKEN_FAILURE";

export const GET_SITE_TOKEN_CALCULATION = "GET_SITE_TOKEN_CALCULATION";
export const GET_SITE_TOKEN_CALCULATION_SUCCESS = "GET_SITE_TOKEN_CALCULATION_SUCCESS";
export const GET_SITE_TOKEN_CALCULATION_FAILURE = "GET_SITE_TOKEN_CALCULATION_FAILURE";

export const SITE_TOKEN_CONVERSION = "SITE_TOKEN_CONVERSION";
export const SITE_TOKEN_CONVERSION_SUCCESS = "SITE_TOKEN_CONVERSION_SUCCESS";
export const SITE_TOKEN_CONVERSION_FAILURE = "SITE_TOKEN_CONVERSION_FAILURE";


// add by Tejas for get currency data 12/2/2019
export const GET_CURRENCY_DATA = "GET_CURRENCY_DATA";
export const GET_CURRENCY_DATA_SUCCESS = "GET_CURRENCY_DATA_SUCCESS";
export const GET_CURRENCY_DATA_FAILURE = "GET_CURRENCY_DATA_FAILURE";
// Added By Megha Kariya (13/02/2019)
export const GET_SOCIAL_MEDIA_DETAIL = "GET_SOCIAL_MEDIA_DETAIL";
export const GET_SOCIAL_MEDIA_DETAIL_SUCCESS = "GET_SOCIAL_MEDIA_DETAIL_SUCCESS";
export const GET_SOCIAL_MEDIA_DETAIL_FAILURE = "GET_SOCIAL_MEDIA_DETAIL_FAILURE";

/* Margin Trading - Wallet Constants - added by Nishant */
export const LIST_MARGIN_WALLETS = "LIST_MARGIN_WALLETS";
export const LIST_MARGIN_WALLETS_SUCCESS = "LIST_MARGIN_WALLETS_SUCCESS";
export const LIST_MARGIN_WALLETS_FAILURE = "LIST_MARGIN_WALLETS_FAILURE";

/* Create a margin wallet - added by Nishant */
export const CREATE_MARGIN_WALLETS = "CREATE_MARGIN_WALLETS";
export const CREATE_MARGIN_WALLETS_SUCCESS = "CREATE_MARGIN_WALLETS_SUCCESS";
export const CREATE_MARGIN_WALLETS_FAILURE = "CREATE_MARGIN_WALLETS_FAILURE";

/* Add leverage request - added by Nishant */
export const ADD_LEVERAGE = "ADD_LEVERAGE";
export const ADD_LEVERAGE_SUCCESS = "ADD_LEVERAGE_SUCCESS";
export const ADD_LEVERAGE_FAILURE = "ADD_LEVERAGE_FAILURE";
/* Add leverage confirm request - added by Nishant */
export const ADD_LEVERAGE_CONFIRMATION = "ADD_LEVERAGE_CONFIRMATION";
export const ADD_LEVERAGE_CONFIRMATION_SUCCESS = "ADD_LEVERAGE_CONFIRMATION_SUCCESS";
export const ADD_LEVERAGE_CONFIRMATION_FAILURE = "ADD_LEVERAGE_CONFIRMATION_FAILURE";

/* margin wallet ledger - added by vishva */
export const MARGIN_WALLET_LEDGER = "MARGIN_WALLET_LEDGER";
export const MARGIN_WALLET_LEDGER_SUCCESS = "MARGIN_WALLET_LEDGER_SUCCESS";
export const MARGIN_WALLET_LEDGER_FAILURE = "MARGIN_WALLET_LEDGER_FAILURE";

/*Create Type For Referral Program - added by Sanjay */
export const GET_REFERRAL_CODE = "GET_REFERRAL_CODE";
export const GET_REFERRAL_CODE_SUCCESS = "GET_REFERRAL_CODE_SUCCESS";
export const GET_REFERRAL_CODE_FAILURE = "GET_REFERRAL_CODE_FAILURE";

export const GET_COUNT_REFERRAL_DASHBOARD = "GET_COUNT_REFERRAL_DASHBOARD";
export const GET_COUNT_REFERRAL_DASHBOARD_SUCCESS = "GET_COUNT_REFERRAL_DASHBOARD_SUCCESS";
export const GET_COUNT_REFERRAL_DASHBOARD_FAILURE = "GET_COUNT_REFERRAL_DASHBOARD_FAILURE";

export const GET_REFERRAL_INVITE_LIST = "GET_REFERRAL_INVITE_LIST";
export const GET_REFERRAL_INVITE_LIST_SUCCESS = "GET_REFERRAL_INVITE_LIST_SUCCESS";
export const GET_REFERRAL_INVITE_LIST_FAILURE = "GET_REFERRAL_INVITE_LIST_FAILURE";

export const GET_CHANNEL_TYPE = "GET_CHANNEL_TYPE";
export const GET_CHANNEL_TYPE_SUCCESS = "GET_CHANNEL_TYPE_SUCCESS";
export const GET_CHANNEL_TYPE_FAILURE = "GET_CHANNEL_TYPE_FAILURE";

export const GET_SERVICE_LIST = "GET_SERVICE_LIST";
export const GET_SERVICE_LIST_SUCCESS = "GET_SERVICE_LIST_SUCCESS";
export const GET_SERVICE_LIST_FAILURE = "GET_SERVICE_LIST_FAILURE";

export const GET_PAY_TYPE = "GET_PAY_TYPE";
export const GET_PAY_TYPE_SUCCESS = "GET_PAY_TYPE_SUCCESS";
export const GET_PAY_TYPE_FAILURE = "GET_PAY_TYPE_FAILURE";

export const GET_REFERRAL_PARTICIPATE_LIST = "GET_REFERRAL_PARTICIPATE_LIST";
export const GET_REFERRAL_PARTICIPATE_LIST_SUCCESS = "GET_REFERRAL_PARTICIPATE_LIST_SUCCESS";
export const GET_REFERRAL_PARTICIPATE_LIST_FAILURE = "GET_REFERRAL_PARTICIPATE_LIST_FAILURE";

export const GET_REFERRAL_INVITE_BY_CHANNEL = "GET_REFERRAL_INVITE_BY_CHANNEL";
export const GET_REFERRAL_INVITE_BY_CHANNEL_SUCCESS = "GET_REFERRAL_INVITE_BY_CHANNEL_SUCCESS";
export const GET_REFERRAL_INVITE_BY_CHANNEL_FAILURE = "GET_REFERRAL_INVITE_BY_CHANNEL_FAILURE";

export const GET_REFERRAL_URL = "GET_REFERRAL_URL";
export const GET_REFERRAL_URL_SUCCESS = "GET_REFERRAL_URL_SUCCESS";
export const GET_REFERRAL_URL_FAILURE = "GET_REFERRAL_URL_FAILURE";

// add by Tejas for Get View APi plan data 26/2/2019
export const GET_API_PLAN_DATA = "GET_API_PLAN_DATA";
export const GET_API_PLAN_DATA_SUCCESS = "GET_API_PLAN_DATA_SUCCESS";
export const GET_API_PLAN_DATA_FAILURE = "GET_API_PLAN_DATA_FAILURE";

//Added by Sanjay For Send Referral Invite By Email and SMS

export const SEND_REFERRAL_BY_EMAIL = "SEND_REFERRAL_BY_EMAIL";
export const SEND_REFERRAL_BY_EMAIL_SUCCESS = "SEND_REFERRAL_BY_EMAIL_SUCCESS";
export const SEND_REFERRAL_BY_EMAIL_FAILURE = "SEND_REFERRAL_BY_EMAIL_FAILURE";

export const SEND_REFERRAL_BY_SMS = "SEND_REFERRAL_BY_SMS";
export const SEND_REFERRAL_BY_SMS_SUCCESS = "SEND_REFERRAL_BY_SMS_SUCCESS";
export const SEND_REFERRAL_BY_SMS_FAILURE = "SEND_REFERRAL_BY_SMS_FAILURE";

// add by Tejas for subscribe plan  28/2/2019 
export const SUBSCRIBE_API_PLAN = "SUBSCRIBE_API_PLAN";
export const SUBSCRIBE_API_PLAN_SUCCESS = "SUBSCRIBE_API_PLAN_SUCCESS";
export const SUBSCRIBE_API_PLAN_FAILURE = "SUBSCRIBE_API_PLAN_FAILURE";

// add by Tejas for User Active PLan plan  1/3/2019 
export const GET_USER_ACTIVE_PLAN = "GET_USER_ACTIVE_PLAN";
export const GET_USER_ACTIVE_PLAN_SUCCESS = "GET_USER_ACTIVE_PLAN_SUCCESS";
export const GET_USER_ACTIVE_PLAN_FAILURE = "GET_USER_ACTIVE_PLAN_FAILURE";

// add by Tejas for Set Auto Renewal plan 1/3/2019 
export const SET_AUTO_RENEWAL_PLAN = "SET_AUTO_RENEWAL_PLAN";
export const SET_AUTO_RENEWAL_PLAN_SUCCESS = "SET_AUTO_RENEWAL_PLAN_SUCCESS";
export const SET_AUTO_RENEWAL_PLAN_FAILURE = "SET_AUTO_RENEWAL_PLAN_FAILURE";

// add by Tejas for stop Auto Renewal plan 1/3/2019 
export const STOP_AUTO_RENEWAL_PLAN = "STOP_AUTO_RENEWAL_PLAN";
export const STOP_AUTO_RENEWAL_PLAN_SUCCESS = "STOP_AUTO_RENEWAL_PLAN_SUCCESS";
export const STOP_AUTO_RENEWAL_PLAN_FAILURE = "STOP_AUTO_RENEWAL_PLAN_FAILURE";

// added by devang parekh for display leverage info in margin dashboard 6-3-2019
export const GET_LEVERAGE_DETAIL = "GET_LEVERAGE_DETAIL";
export const GET_LEVERAGE_DETAIL_SUCCESS = "GET_LEVERAGE_DETAIL_SUCCESS";
export const GET_LEVERAGE_DETAIL_FAILURE = "GET_LEVERAGE_DETAIL_FAILURE";

//Leverage Report added by parth andhariya 
export const GET_LEVERAGE_REPORT_LIST = "GET_LEVERAGE_REPORT_LIST";
export const GET_LEVERAGE_REPORT_LIST_SUCCESS = "GET_LEVERAGE_REPORT_LIST_SUCCESS";
export const GET_LEVERAGE_REPORT_LIST_FAILURE = "GET_LEVERAGE_REPORT_LIST_FAILURE";

//added By Sanjay For Referral URL Click 
export const REFERRAL_URL_CLICK = "REFERRAL_URL_CLICK";
export const REFERRAL_URL_CLICK_SUCCESS = "REFERRAL_URL_CLICK_SUCCESS";
export const REFERRAL_URL_CLICK_FAILURE = "REFERRAL_URL_CLICK_FAILURE";

export const CLICK_REFERRAL_LINK_REPORT = "CLICK_REFERRAL_LINK_REPORT";
export const CLICK_REFERRAL_LINK_REPORT_SUCCESS = "CLICK_REFERRAL_LINK_REPORT_SUCCESS";
export const CLICK_REFERRAL_LINK_REPORT_FAILURE = "CLICK_REFERRAL_LINK_REPORT_FAILURE";

export const REFERRAL_REWARD_REPORT = "REFERRAL_REWARD_REPORT";
export const REFERRAL_REWARD_REPORT_SUCCESS = "REFERRAL_REWARD_REPORT_SUCCESS";
export const REFERRAL_REWARD_REPORT_FAILURE = "REFERRAL_REWARD_REPORT_FAILURE";

export const GET_REFERRAL_SERVICE = "GET_REFERRAL_SERVICE";
export const GET_REFERRAL_SERVICE_SUCCESS = "GET_REFERRAL_SERVICE_SUCCESS";
export const GET_REFERRAL_SERVICE_FAILURE = "GET_REFERRAL_SERVICE_FAILURE";

/* get withdrawal trn policy - added by nishant */
export const WITHDRAW_POLICY = "WITHDRAW_POLICY";
export const WITHDRAW_POLICY_SUCCESS = "WITHDRAW_POLICY_SUCCESS";
export const WITHDRAW_POLICY_FAILURE = "WITHDRAW_POLICY_FAILURE";

// add by Tejas for Get Api Key List 7/3/2019 
export const GET_API_KEY_LIST = "GET_API_KEY_LIST";
export const GET_API_KEY_LIST_SUCCESS = "GET_API_KEY_LIST_SUCCESS";
export const GET_API_KEY_LIST_FAILURE = "GET_API_KEY_LIST_FAILURE";

// add by Tejas for Add Ip Address List 8/3/2019 
export const ADD_IP_ADDRESS = "ADD_IP_ADDRESS";
export const ADD_IP_ADDRESS_SUCCESS = "ADD_IP_ADDRESS_SUCCESS";
export const ADD_IP_ADDRESS_FAILURE = "ADD_IP_ADDRESS_FAILURE";

// add by Tejas for Update Api Key List 8/3/2019 
export const UPDATE_API_KEY_LIST = "UPDATE_API_KEY_LIST";
export const UPDATE_API_KEY_LIST_SUCCESS = "UPDATE_API_KEY_LIST_SUCCESS";
export const UPDATE_API_KEY_LIST_FAILURE = "UPDATE_API_KEY_LIST_FAILURE";

// add by Tejas for Generate Api Key List 8/3/2019 
export const GENERATE_API_KEY = "GENERATE_API_KEY";
export const GENERATE_API_KEY_SUCCESS = "GENERATE_API_KEY_SUCCESS";
export const GENERATE_API_KEY_FAILURE = "GENERATE_API_KEY_FAILURE";

// add by Tejas for delete  Api Key List 9/3/2019 
export const DELETE_API_KEY = "DELETE_API_KEY";
export const DELETE_API_KEY_SUCCESS = "DELETE_API_KEY_SUCCESS";
export const DELETE_API_KEY_FAILURE = "DELETE_API_KEY_FAILURE";

// add by Tejas for get ip whitelist data list 9/3/2019 
export const GET_IP_WHITELIST_DATA = "GET_IP_WHITELIST_DATA";
export const GET_IP_WHITELIST_DATA_SUCCESS = "GET_IP_WHITELIST_DATA_SUCCESS";
export const GET_IP_WHITELIST_DATA_FAILURE = "GET_IP_WHITELIST_DATA_FAILURE";

// add by Tejas for REMOVE Ip Address List 8/3/2019 
export const REMOVE_IP_ADDRESS = "REMOVE_IP_ADDRESS";
export const REMOVE_IP_ADDRESS_SUCCESS = "REMOVE_IP_ADDRESS_SUCCESS";
export const REMOVE_IP_ADDRESS_FAILURE = "REMOVE_IP_ADDRESS_FAILURE";

// add by Tejas for GET Auto Renewal plan 12/3/2019 
export const GET_AUTO_RENEWAL_PLAN = "GET_AUTO_RENEWAL_PLAN";
export const GET_AUTO_RENEWAL_PLAN_SUCCESS = "GET_AUTO_RENEWAL_PLAN_SUCCESS";
export const GET_AUTO_RENEWAL_PLAN_FAILURE = "GET_AUTO_RENEWAL_PLAN_FAILURE";

// add by Tejas for sET MANUAL RENEW plan 13/3/2019 
export const SET_MANUAL_RENEWAL_PLAN = "SET_MANUAL_RENEWAL_PLAN";
export const SET_MANUAL_RENEWAL_PLAN_SUCCESS = "SET_MANUAL_RENEWAL_PLAN_SUCCESS";
export const SET_MANUAL_RENEWAL_PLAN_FAILURE = "SET_MANUAL_RENEWAL_PLAN_FAILURE";

// add by Tejas for Get Custom Limits 14/3/2019 
export const GET_CUSTOM_LIMITS = "GET_CUSTOM_LIMITS";
export const GET_CUSTOM_LIMITS_SUCCESS = "GET_CUSTOM_LIMITS_SUCCESS";
export const GET_CUSTOM_LIMITS_FAILURE = "GET_CUSTOM_LIMITS_FAILURE";

// add by Tejas for  Set Custom Limits 14/3/2019 
export const SET_CUSTOM_LIMITS = "SET_CUSTOM_LIMITS";
export const SET_CUSTOM_LIMITS_SUCCESS = "SET_CUSTOM_LIMITS_SUCCESS";
export const SET_CUSTOM_LIMITS_FAILURE = "SET_CUSTOM_LIMITS_FAILURE";

// add by Tejas for  Update Custom Limits 14/3/2019 
export const UPDATE_CUSTOM_LIMITS = "UPDATE_CUSTOM_LIMITS";
export const UPDATE_CUSTOM_LIMITS_SUCCESS = "UPDATE_CUSTOM_LIMITS_SUCCESS";
export const UPDATE_CUSTOM_LIMITS_FAILURE = "UPDATE_CUSTOM_LIMITS_FAILURE";

// add by Tejas for  Set Default Limits 14/3/2019 
export const SET_DEFAULT_CUSTOM_LIMITS = "SET_DEFAULT_CUSTOM_LIMITS";
export const SET_DEFAULT_CUSTOM_LIMITS_SUCCESS = "SET_DEFAULT_CUSTOM_LIMITS_SUCCESS";
export const SET_DEFAULT_CUSTOM_LIMITS_FAILURE = "SET_DEFAULT_CUSTOM_LIMITS_FAILURE";


// add by Tejas for Get Api Key id List 22/3/2019 
export const GET_API_KEY_BY_ID = "GET_API_KEY_BY_ID";
export const GET_API_KEY_BY_ID_SUCCESS = "GET_API_KEY_BY_ID_SUCCESS";
export const GET_API_KEY_BY_ID_FAILURE = "GET_API_KEY_BY_ID_FAILURE";
//added by parth andhariya
export const GET_LEVERAGE_BASE_CURRENCY = "GET_LEVERAGE_BASE_CURRENCY";
export const GET_LEVERAGE_BASE_CURRENCY_SUCCESS = "GET_LEVERAGE_BASE_CURRENCY_SUCCESS";
export const GET_LEVERAGE_BASE_CURRENCY_FAILURE = "GET_LEVERAGE_BASE_CURRENCY_FAILURE";
//added by vishva 
export const PROFIT_LOSS_LIST = "PROFIT_LOSS_LIST";
export const PROFIT_LOSS_LIST_SUCCESS = "PROFIT_LOSS_LIST_SUCCESS";
export const PROFIT_LOSS_LIST_FAILURE = "PROFIT_LOSS_LIST_FAILURE";
//added by vishva 
export const DELEVERAGE_PRECONFIRM = "DELEVERAGE_PRECONFIRM";
export const DELEVERAGE_PRECONFIRM_SUCCESS = "DELEVERAGE_PRECONFIRM_SUCCESS";
export const DELEVERAGE_PRECONFIRM_FAILURE = "DELEVERAGE_PRECONFIRM_FAILURE";

export const DELEVERAGE_CONFIRM = "DELEVERAGE_CONFIRM";
export const DELEVERAGE_CONFIRM_SUCCESS = "DELEVERAGE_CONFIRM_SUCCESS";
export const DELEVERAGE_CONFIRM_FAILURE = "DELEVERAGE_CONFIRM_FAILURE";
//added by vishva
export const UPGRADE_LOAN = "UPGRADE_LOAN";
export const UPGRADE_LOAN_SUCCESS = "UPGRADE_LOAN_SUCCESS";
export const UPGRADE_LOAN_FAILURE = "UPGRADE_LOAN_FAILURE";

//added by parth andhariya 16-04-2019
export const GET_BASE_MARKET_CURRENCY = "GET_BASE_MARKET_CURRENCY";
export const GET_BASE_MARKET_CURRENCY_SUCCESS = "GET_BASE_MARKET_CURRENCY_SUCCESS";
export const GET_BASE_MARKET_CURRENCY_FAILURE = "GET_BASE_MARKET_CURRENCY_FAILURE";

//added by parth andhariya 22-04-2019
export const GET_OPEN_POSITION_REPORT_LIST = "GET_OPEN_POSITION_REPORT_LIST";
export const GET_OPEN_POSITION_REPORT_LIST_SUCCESS = "GET_OPEN_POSITION_REPORT_LIST_SUCCESS";
export const GET_OPEN_POSITION_REPORT_LIST_FAILURE = "GET_OPEN_POSITION_REPORT_LIST_FAILURE";

// added by Tejas for Arbitrage Buyer order Date : 3/6/2019
//Trade History Report
export const ARBITRAGE_TRADE_HISTORY_REPORT = "ARBITRAGE_TRADE_HISTORY_REPORT";
export const ARBITRAGE_TRADE_HISTORY_REPORT_SUCCESS = "ARBITRAGE_TRADE_HISTORY_REPORT_SUCCESS";
export const ARBITRAGE_TRADE_HISTORY_REPORT_FAILURE = "ARBITRAGE_TRADE_HISTORY_REPORT_FAILURE";

//Open Order Report
export const ARBITRAGE_OPEN_ORDER_REPORT = "ARBITRAGE_OPEN_ORDER_REPORT";
export const ARBITRAGE_OPEN_ORDER_REPORT_SUCCESS = "ARBITRAGE_OPEN_ORDER_REPORT_SUCCESS";
export const ARBITRAGE_OPEN_ORDER_REPORT_FAILURE = "ARBITRAGE_OPEN_ORDER_REPORT_FAILURE";

//Active Order Report
export const ARBITRAGE_ACTIVE_ORDER_REPORT = "ARBITRAGE_ACTIVE_ORDER_REPORT";
export const ARBITRAGE_ACTIVE_ORDER_REPORT_SUCCESS = "ARBITRAGE_ACTIVE_ORDER_REPORT_SUCCESS";
export const ARBITRAGE_ACTIVE_ORDER_REPORT_FAILURE = "ARBITRAGE_ACTIVE_ORDER_REPORT_FAILURE";

//Recent Order Report
export const ARBITRAGE_RECENT_ORDER_REPORT = "ARBITRAGE_RECENT_ORDER_REPORT";
export const ARBITRAGE_RECENT_ORDER_REPORT_SUCCESS = "ARBITRAGE_RECENT_ORDER_REPORT_SUCCESS";
export const ARBITRAGE_RECENT_ORDER_REPORT_FAILURE = "ARBITRAGE_RECENT_ORDER_REPORT_FAILURE";

/************************ End Arbitrage *************************/
//added by vishva
export const GET_ARBITRAGELEDGER_LIST = "GET_ARBITRAGELEDGER_LIST";
export const GET_ARBITRAGELEDGER_LIST_SUCCESS = "GET_ARBITRAGELEDGER_LIST_SUCCESS";
export const GET_ARBITRAGELEDGER_LIST_FAILURE = "GET_ARBITRAGELEDGER_LIST_FAILURE";
//added by vishva
export const LIST_ARBITRAGE_WALLETS = "LIST_ARBITRAGE_WALLETS";
export const LIST_ARBITRAGE_WALLETS_SUCCESS = "LIST_ARBITRAGE_WALLETS_SUCCESS";
export const LIST_ARBITRAGE_WALLETS_FAILURE = "LIST_ARBITRAGE_WALLETS_FAILURE";
export const CREATE_ARBITRAGE_WALLETS = "CREATE_ARBITRAGE_WALLETS";
export const CREATE_ARBITRAGE_WALLETS_SUCCESS = "CREATE_ARBITRAGE_WALLETS_SUCCESS";
export const CREATE_ARBITRAGE_WALLETS_FAILURE = "CREATE_ARBITRAGE_WALLETS_FAILURE";
//add leverage preconfirmation
export const ADD_LEVERAGE_PRECONFIRMATION = "ADD_LEVERAGE_PRECONFIRMATION";
export const ADD_LEVERAGE_PRECONFIRMATION_SUCCESS = "ADD_LEVERAGE_PRECONFIRMATION_SUCCESS";
export const ADD_LEVERAGE_PRECONFIRMATION_FAILURE = "ADD_LEVERAGE_PRECONFIRMATION_FAILURE";
//confirm leverage request
export const ADD_ARBITRAGE_LEVERAGE = "ADD_ARBITRAGE_LEVERAGE";
export const ADD_ARBITRAGE_LEVERAG_SUCCESS = "ADD_ARBITRAGE_LEVERAG_SUCCESS";
export const ADD_ARBITRAGE_LEVERAGE_FAILURE = "ADD_ARBITRAGE_LEVERAGE_FAILURE";
//list arbitrage currency - added by vishva
export const LIST_ARBITRAGE_CURRENCY = "LIST_ARBITRAGE_CURRENCY";
export const LIST_ARBITRAGE_CURRENCY_SUCCESS = "LIST_ARBITRAGE_CURRENCY_SUCCESS";
export const LIST_ARBITRAGE_CURRENCY_FAILURE = "LIST_ARBITRAGE_CURRENCY_FAILURE";

// added by Tejas for Arbitrage Buyer order Date : 3/6/2019
export const ARBITRAGE_BUYER_BOOK_LIST = "ARBITRAGE_BUYER_BOOK_LIST";
export const ARBITRAGE_BUYER_BOOK_LIST_SUCCESS = "ARBITRAGE_BUYER_BOOK_LIST_SUCCESS";
export const ARBITRAGE_BUYER_BOOK_LIST_FAILURE = "ARBITRAGE_BUYER_BOOK_LIST_FAILURE";

// added by Tejas for Arbitrage sELLER order Date : 3/6/2019
export const ARBITRAGE_SELLER_BOOK_LIST = "ARBITRAGE_SELLER_BOOK_LIST";
export const ARBITRAGE_SELLER_BOOK_LIST_SUCCESS = "ARBITRAGE_SELLER_BOOK_LIST_SUCCESS";
export const ARBITRAGE_SELLER_BOOK_LIST_FAILURE = "ARBITRAGE_SELLER_BOOK_LIST_FAILURE";

// added by Tejas for Pair List Date : 4/6/2019
export const ARBITRAGE_PAIR_LIST = "ARBITRAGE_PAIR_LIST";
export const ARBITRAGE_PAIR_LIST_SUCCESS = "ARBITRAGE_PAIR_LIST_SUCCESS";
export const ARBITRAGE_PAIR_LIST_FAILURE = "ARBITRAGE_PAIR_LIST_FAILURE";

// added by Tejas for Chart Data Date : 4/6/2019
export const ARBITRAGE_CHART_DATA = "ARBITRAGE_CHART_DATA";
export const ARBITRAGE_CHART_DATA_SUCCESS = "ARBITRAGE_CHART_DATA_SUCCESS";
export const ARBITRAGE_CHART_DATA_FAILURE = "ARBITRAGE_CHART_DATA_FAILURE";

// added by Tejas for Place Order Date : 4/6/2019
export const ARBITRAGE_PLACE_ORDER = "ARBITRAGE_PLACE_ORDER";
export const ARBITRAGE_PLACE_ORDER_SUCCESS = "ARBITRAGE_PLACE_ORDER_SUCCESS";
export const ARBITRAGE_PLACE_ORDER_FAILURE = "ARBITRAGE_PLACE_ORDER_FAILURE";

// added by devnag parekh (7-6-2019)
export const GET_ARBITRAGE_PROFITINDICATOR = "GET_ARBITRAGE_PROFITINDICATOR";
export const GET_ARBITRAGE_PROFITINDICATOR_SUCCESS = "GET_ARBITRAGE_PROFITINDICATOR_SUCCESS";
export const GET_ARBITRAGE_PROFITINDICATOR_FAILURE = "GET_ARBITRAGE_PROFITINDICATOR_FAILURE";

//cancel open order Add by Tejas (Merge code of Jayshreeba Gohil ) 8/6/2019
export const DO_CANCEL_ORDER_ARBITRAGE = "DO_CANCEL_ORDER_ARBITRAGE";
export const DO_CANCEL_ORDER_ARBITRAGE_SUCCESS = "DO_CANCEL_ORDER_ARBITRAGE_SUCCESS";
export const DO_CANCEL_ORDER_ARBITRAGE_FAILURE = "DO_CANCEL_ORDER_ARBITRAGE_FAILURE";


// added by Tejas for Place BUlk Order Date : 4/6/2019
export const ARBITRAGE_PLACE_BULK_ORDER = "ARBITRAGE_PLACE_BULK_ORDER";
export const ARBITRAGE_PLACE_BULK_ORDER_SUCCESS = "ARBITRAGE_PLACE_BULK_ORDER_SUCCESS";
export const ARBITRAGE_PLACE_BULK_ORDER_FAILURE = "ARBITRAGE_PLACE_BULK_ORDER_FAILURE";

// added by Tejas for Arbitrage Trade Order Date : 11/6/2019
export const ARBITRAGE_TRADE_ORDER = "ARBITRAGE_TRADE_ORDER";
export const ARBITRAGE_TRADE_ORDER_SUCCESS = "ARBITRAGE_TRADE_ORDER_SUCCESS";
export const ARBITRAGE_TRADE_ORDER_FAILURE = "ARBITRAGE_TRADE_ORDER_FAILURE";

// added by Tejas for Arbitrage Market Trade History Date : 12/6/2019
export const ARBITRAGE_MARKET_TRADE_HISTORY = "ARBITRAGE_MARKET_TRADE_HISTORY";
export const ARBITRAGE_MARKET_TRADE_HISTORY_SUCCESS = "ARBITRAGE_MARKET_TRADE_HISTORY_SUCCESS";
export const ARBITRAGE_MARKET_TRADE_HISTORY_FAILURE = "ARBITRAGE_MARKET_TRADE_HISTORY_FAILURE";

// added by Tejas for Arbitrage Exchange List Date : 12/6/2019
export const ARBITRAGE_EXCHANGE_LIST = "ARBITRAGE_EXCHANGE_LIST";
export const ARBITRAGE_EXCHANGE_LIST_SUCCESS = "ARBITRAGE_EXCHANGE_LIST_SUCCESS";
export const ARBITRAGE_EXCHANGE_LIST_FAILURE = "ARBITRAGE_EXCHANGE_LIST_FAILURE";

// added by salim for list exchange smart arbitrage Date : 12/6/2019
export const LIST_EXCHANGE_SMART_ARBITRAGE = "LIST_EXCHANGE_SMART_ARBITRAGE";
export const LIST_EXCHANGE_SMART_ARBITRAGE_SUCCESS = "LIST_EXCHANGE_SMART_ARBITRAGE_SUCCESS";
export const LIST_EXCHANGE_SMART_ARBITRAGE_FAILURE = "LIST_EXCHANGE_SMART_ARBITRAGE_FAILURE";

// added by nishant for add balance from main wallet to arbitage 13-06-2019
export const ARBITRAGE_ADD_WALLET_BALANCE = "ARBITRAGE_ADD_WALLET_BALANCE";
export const ARBITRAGE_ADD_WALLET_BALANCE_SUCCESS = "ARBITRAGE_ADD_WALLET_BALANCE_SUCCESS";
export const ARBITRAGE_ADD_WALLET_BALANCE_FAILURE = "ARBITRAGE_ADD_WALLET_BALANCE_FAILURE";
//added  by vishva shah
export const GET_ANALYTICSGRAPH_RECORD = "GET_ANALYTICSGRAPH_RECORD";
export const GET_ANALYTICSGRAPH_RECORD_SUCCESS = "GET_ANALYTICSGRAPH_RECORD_SUCCESS"
export const GET_ANALYTICSGRAPH_RECORD_FAILURE = "GET_ANALYTICSGRAPH_RECORD_FAILURE";
