// DataTable with data

export const myTableData = [{id:0, region:"South America", sector:"Banking", channel:"VARs", units:4, customer:"Beacon Systems", product:"EnviroCare Max", amount:10294, discount:0.279, saleDate:"2016-02-29", shipped:false}, {id:1, region:"North America", sector:"Health", channel:"Telecom", units:4, customer:"Global Services", product:"EnviroCare", amount:2895, discount:0.264, saleDate:"2016-02-08", shipped:true}, {id:2, region:"North America", sector:"Health", channel:"Telecom", units:2, customer:"Supply Warehouse", product:"EnviroCare Max", amount:3503, discount:0.447, saleDate:"2016-02-06", shipped:true}, {id:3, region:"Australia", sector:"Banking", channel:"VARs", units:1, customer:"Apollo Inc", product:"SolarOne", amount:1379, discount:0.43, saleDate:"2016-04-30", shipped:true}, {id:4, region:"Europe", sector:"Health", channel:"Retail", units:2, customer:"Beacon Systems", product:"SolarOne", amount:2867, discount:0.019, saleDate:"2016-03-30", shipped:true}, {id:5, region:"South America", sector:"Banking", channel:"Resellers", units:2, customer:"Discovery Systems", product:"EnviroCare", amount:3365, discount:0.481, saleDate:"2016-02-08", shipped:true}, {id:6, region:"North America", sector:"Health", channel:"VARs", units:4, customer:"Renewable Supplies", product:"EnviroCare", amount:6932, discount:0.128, saleDate:"2016-03-13", shipped:true}, {id:7, region:"Europe", sector:"Telecom", channel:"Direct", units:1, customer:"Building M Inc", product:"EnviroCare", amount:1135, discount:0.348, saleDate:"2016-02-09", shipped:false}, {id:8, region:"Australia", sector:"Banking", channel:"Telecom", units:2, customer:"Renewable Supplies", product:"EnviroCare", amount:1343, discount:0.228, saleDate:"2016-02-09", shipped:true}, {id:9, region:"North America", sector:"Energy", channel:"Consultants", units:2, customer:"Apollo Inc", product:"EnviroCare", amount:10993, discount:0.397, saleDate:"2016-03-22", shipped:true}, {id:10, region:"South America", sector:"Health", channel:"VARs", units:4, customer:"McCord Builders", product:"SolarMax", amount:1501, discount:0.408, saleDate:"2016-04-22", shipped:true}, {id:11, region:"North America", sector:"Energy", channel:"Resellers", units:2, customer:"Renewable Supplies", product:"EnviroCare Max", amount:9573, discount:0.328, saleDate:"2016-04-07", shipped:true}, {id:12, region:"North America", sector:"Insurance", channel:"Consultants", units:4, customer:"Environment Solar", product:"EnviroCare", amount:1236, discount:0.034, saleDate:"2016-04-05", shipped:false}, {id:13, region:"North America", sector:"Insurance", channel:"Consultants", units:4, customer:"Environment Solar", product:"EnviroCare", amount:1236, discount:0.034, saleDate:"2016-04-05", shipped:false}];
export const myTableDataColumns = [
    { name: 'customer', title: 'Customer123' },
    { name: 'product', title: 'Product' },
    { name: 'units', title: 'Units' },
    { name: 'shipped', title: 'Shipped', dataType: 'boolean' },
    { name: 'sector' ,title:'SECTOR'},
  ]; 